### ISSUE TITLE
AttributeError: module 'tqdm' has no attribute '__version__'

### ISSUE THREAD

**Issue by naturalstupid** [tqdm/tqdm#1038]
I am tryng to upload my first python package to TestPyPi per instructions provided  in
https://packaging.python.org/tutorials/packaging-projects/
When I executed the following command:
python3 -m twine upload --repository testpypi dist/*
I get the below error. Following is the full trae info:
AttributeError: module 'tqdm' has no attribute '__version__'
---
Traceback (most recent call last):
  File "D:\LaptopBackup\Local\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\LaptopBackup\Local\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\LaptopBackup\Local\Anaconda\lib\site-packages\twine\__main__.py", line 53, in <module>
    sys.exit(main())
  File "D:\LaptopBackup\Local\Anaconda\lib\site-packages\twine\__main__.py", line 28, in main
    result = cli.dispatch(sys.argv[1:])
  File "D:\LaptopBackup\Local\Anaconda\lib\site-packages\twine\cli.py", line 62, in dispatch
    version="%(prog)s version {} ({})".format(twine.__version__, dep_versions()),
  File "D:\LaptopBackup\Local\Anaconda\lib\site-packages\twine\cli.py", line 52, in dep_versions
    "{}: {}".format(*dependency) for dependency in list_dependencies_and_versions()
  File "D:\LaptopBackup\Local\Anaconda\lib\site-packages\twine\cli.py", line 46, in list_dependencies_and_versions
    ("tqdm", tqdm.__version__),
AttributeError: module 'tqdm' has no attribute '__version__'
--------
I have tqd - (4.46.0)
Any help appreciated.

**Comment by casperdcl** [comment]
Did you really run `python3 -m pip install --user --upgrade twine` first? How do you know the `tqdm` version? What happens if you do `python3 -m tqdm --version`?

**Comment by naturalstupid** [comment]
Yes
I got the tqdm version from same command above and I mentioned the same in the issue as it may help you.

**Comment by casperdcl** [comment]
There's a massive difference between `python` and `python3`.

Please check you're using the same one everywhere.

**Comment by naturalstupid** [comment]
FYI - I have a Windows system. I added python path to system path. 
I have python 3.6 installed in my system
python works from command line
python3 does not. I thought both are one and the same so I always use python
I did not know python and pthyon3 are different
Let me see which path has python3.exe and add that to path.
