### ISSUE TITLE
Pylint crashes after 4.48.0

### ISSUE THREAD

**Issue by pwwang** [tqdm/tqdm#1049]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
See also here: https://github.com/PyTorchLightning/pytorch-lightning/issues/4039

The minimal example is mention here: https://github.com/PyTorchLightning/pytorch-lightning/issues/4039#issuecomment-706568078 and below:
```python
from tqdm.auto import tqdm  # pylint error only with auto
bar = tqdm()
bar.total = 1
```

With the above example, pylint crashed:
<details>
<pre>
<code>
Traceback (most recent call last):
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/decorators.py", line 32, in cached
    return cache[func]
KeyError: <bound method ClassDef.slots of <ClassDef.tqdm l.31 at 0x7f31996d9940>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1031, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/manager.py", line 98, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/builder.py", line 138, in file_build
    return self._post_build(module, encoding)
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/builder.py", line 158, in _post_build
    self.delayed_assattr(delayed)
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/builder.py", line 234, in delayed_assattr
    if not _can_assign_attr(inferred, node.attrname):
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/builder.py", line 59, in _can_assign_attr
    slots = node.slots()
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/decorators.py", line 34, in cached
    cache[func] = result = func(*args, **kwargs)
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/scoped_nodes.py", line 2833, in slots
    slots = list(grouped_slots())
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/scoped_nodes.py", line 2818, in grouped_slots
    for cls in self.mro()[:-1]:
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/scoped_nodes.py", line 2904, in mro
    return self._compute_mro(context=context)
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/scoped_nodes.py", line 2894, in _compute_mro
    return _c3_merge(unmerged_mro, self, context)
  File "/home/pwwang/.cache/pypoetry/virtualenvs/prog-taq1idOW-py3.8/lib/python3.8/site-packages/astroid/scoped_nodes.py", line 83, in _c3_merge
    raise exceptions.InconsistentMroError(
astroid.exceptions.InconsistentMroError: Cannot create a consistent method resolution order for MROs (tqdm, Comparable, object), (tqdm_asyncio, tqdm, Comparable, object), (tqdm, tqdm_asyncio) of class <ClassDef.tqdm l.31 at 0x7f31996d9940>.
************* Module tqdm_pylint_error
tqdm_pylint_error.py:1:0: F0002: <class 'astroid.exceptions.InconsistentMroError'>: Cannot create a consistent method resolution order for MROs (tqdm, Comparable, object), (tqdm_asyncio, tqdm, Comparable, object), (tqdm, tqdm_asyncio) of class <ClassDef.tqdm l.31 at 0x7f31996d9940>. (astroid-error)
</code>
</pre>
</details>

Environment:
- tqdm: 4.50.2
- pylint: 2.6.0
- python: 3.8.3 (default, May 19 2020, 18:47:26)
- Platform: [GCC 7.3.0] linux

I have test version 4.48.0 and earlier, which worked fine.

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
Looks like it may be a pylint bug https://github.com/PyCQA/pylint/issues/2188 or https://github.com/PyCQA/pylint/issues/3247.


`tqdm.auto` uses the diamond pattern assuming C3 linearisation (standard Python MRO) which pylint really shouldn't warn about.
