### ISSUE TITLE
nbconvert error

### ISSUE THREAD

**Issue by bknaepen** [tqdm/tqdm#1092]
- [ +] I have marked all applicable categories:
    + [+] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [ +] I have visited the [source website], and in particular
  read the [known issues]
- [+ ] I have searched through the [issue tracker] for duplicates
- [+] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

When I use the command,

```
jupyter nbconvert --to html --execute notebooks.ipynb
```

the following code produces an error:

```
from tqdm.notebook import tqdm
from time import sleep

pbar = tqdm(total=10)

for i in range(5):
    sleep(1)
    pbar.update(1)

pbar.close()
```

The error is: 

```
[NbConvertApp] Converting notebook notebooks.ipynb to html
[NbConvertApp] Executing notebook with kernel: python3
Exception ignored in: <function tqdm.__del__ at 0x7f9156085af0>
Traceback (most recent call last):
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/tqdm/std.py", line 1124, in __del__
    self.close()
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/tqdm/notebook.py", line 271, in close
    self.sp(bar_style='danger')
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/tqdm/notebook.py", line 170, in display
    rtext.value = right
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/traitlets/traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/traitlets/traitlets.py", line 574, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/traitlets/traitlets.py", line 1134, in _notify_trait
    self.notify_change(Bunch(
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipywidgets/widgets/widget.py", line 605, in notify_change
    self.send_state(key=name)
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipywidgets/widgets/widget.py", line 489, in send_state
    self._send(msg, buffers=buffers)
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipywidgets/widgets/widget.py", line 737, in _send
    self.comm.send(data=msg, buffers=buffers)
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipykernel/comm/comm.py", line 122, in send
    self._publish_msg('comm_msg',
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipykernel/comm/comm.py", line 66, in _publish_msg
    self.kernel.session.send(self.kernel.iopub_socket, msg_type,
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/jupyter_client/session.py", line 758, in send
    stream.send_multipart(to_send, copy=copy)
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipykernel/iostream.py", line 264, in send_multipart
    return self.io_thread.send_multipart(*args, **kwargs)
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipykernel/iostream.py", line 214, in send_multipart
    self.schedule(lambda : self._really_send(*args, **kwargs))
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipykernel/iostream.py", line 207, in schedule
    f()
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipykernel/iostream.py", line 214, in <lambda>
    self.schedule(lambda : self._really_send(*args, **kwargs))
  File "/Users/user1/anaconda3/envs/book/lib/python3.8/site-packages/ipykernel/iostream.py", line 222, in _really_send
    self.socket.send_multipart(msg, *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'send_multipart'
[NbConvertApp] Writing 283717 bytes to notebooks.html
```

If I remove the `close()` statement, the error subsists. However, if I use `del(pbar)` instead I get no error.

Versions:
tqdm: 4.51.0 
python: 3.8.5
platform: [Clang 10.0.0 ] darwin
ipython: 7.18.1
jupyter: 1.0.0 
nbconvert: 5.6.1 

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
interesting. Looks like some sort of weird bug with `--execute` and `ipywidgets`. Maybe try executing separately from saving?

**Comment by bknaepen** [comment]
Hi @casperdcl,

Thanks for the feedback.

I have looked around but I did not find how to execute without saving. Could you point me in the right direction?

**Comment by casperdcl** [comment]
I mean `--to notebook --execute` followed by separately `--to html`

**Comment by bknaepen** [comment]
Executing `jupyter nbconvert --to html notebooks.ipynb` does not produce an error. 

However, executing:

`jupyter nbconvert --to notebook --execute notebooks.ipynb` does produce the error reported above.

I have posted the issue in the ipykernel repo since a somewhat similar error was reported: https://github.com/ipython/ipykernel/issues/422
