### ISSUE TITLE
[pytest] ValueError: I/O operation on closed file.

### ISSUE THREAD

**Issue by quancore** [tqdm/tqdm#1170]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:

I have a problem when I use my custom TQDM object on running test cases. It perfectly works with notebooks etc.

parallel.py
```python
import joblib

from psutil import Process, virtual_memory, cpu_count
from tqdm.auto import tqdm as tqdm_auto
from typing import Optional, Union


class TqdmStats(tqdm_auto):
    """Custom tqdm class showing system statistics like cpu and memory use."""

    _empty_desc = "Memory: ? GB/? GB (%?) CPU: %?"
    _desc = "Memory: {:.2f} GB/{:.2f} GB (%{:.2f}) CPU: %{:.2f}"
    _GB = 10**9

    def __init__(self, is_detailed: bool = False, include_childs: bool = True, *args, **kwargs):
        """
        Override desc and get reference to current process

        Parameters
        ----------
        is_detailed: bool
                     Whether tqdm stats report will be in details. If enabled,
                     two extra lines per update will be printed to display common
                     statistics (min, max, std, etc.) for memory and CPU use

        include_childs: bool
                       Whether tqdm stats will include child process memory and CPU
                       use. It could be useful to measure utility stats on multiprocessing case


        Notes
        -----
        if the text is overflow, you can change `ncols` parameter, if not given
        default is 100%
        """
        # prepend original descr with our placeholder text
        original_descr = kwargs.pop("desc", "")
        self._empty_desc = f"{original_descr} | {self._empty_desc}"
        self._desc = f"{original_descr} | {self._desc}"

        # system stats variables
        self.rss_GB = None
        self.total_GB = None
        self.memory_percent = None
        self.cpu_percent = None
        self.is_detailed = is_detailed
        self.include_childs = include_childs

        if self.is_detailed:
            from anofox.utils.online_acc import OnlineAccumulator
            # memory acc. used for memory use in GB
            self.memory_acc = OnlineAccumulator(unit_str="GB")
            # cpu acc. used for cpu percentage use
            self.cpu_acc = OnlineAccumulator(unit_str='%')

        # set dynamic_ncols True for not overflowing especially on notebooks
        if 'dynamic_ncols' not in kwargs:
            kwargs['dynamic_ncols'] = True

        super(TqdmStats, self).__init__(*args, desc=self._empty_desc, **kwargs)
        # initialize the current process as tqdm object process
        # it may be modified in the future
        self._process = Process()

    def __build_stats_str(self):
        """
        Build formatted str based on system stats like mem. use etc.
        and update the accumulator object if there is.
        """
        memory_info = self._process.memory_info()
        # non-swapped physical memory for this process has used
        self.rss_GB = memory_info.rss / self._GB
        self.total_GB = virtual_memory().total / self._GB
        self.memory_percent = self._process.memory_percent()
        self.cpu_percent = (self._process.cpu_percent() / cpu_count()) if cpu_count() else 0

        if self.include_childs:
            for child_process in self._process.children(recursive=True):
                memory_info = child_process.memory_info()
                self.rss_GB += memory_info.rss / self._GB
                self.memory_percent += child_process.memory_percent()
                self.cpu_percent += (child_process.cpu_percent() / cpu_count()) if cpu_count() else 0

        # if there is set a flag for detailed view, update the accumulators
        if self.is_detailed:
            self.memory_acc.add(self.rss_GB)
            self.cpu_acc.add(self.cpu_percent)

        return self._desc.format(self.rss_GB, self.total_GB, self.memory_percent, self.cpu_percent)

    @property
    def process(self):
        raise self._process

    @process.setter
    def process(self, process: Process):
        self._process = process

    def update(self, **kwargs):
        """Calculate RAM usage and update progress bar"""
        current_desc = self.__build_stats_str()
        self.set_description(current_desc)
        if self.is_detailed:
            self.write(f"Memory stats--> curr: {self.rss_GB}GB {self.memory_acc}")
            self.write(f"CPU percentage use stats--> curr: {self.cpu_percent}% {self.cpu_acc}")
            self.write("----------------------------------------------------------------------")
        super(TqdmStats, self).update(**kwargs)


class ParallelTqdm(joblib.Parallel):
    def __init__(self, tqdm_object: Optional[Union[TqdmStats, tqdm_auto]] = None, *args, **kwargs):
        """
        Inherited joblib Parallel implementation with tqdm integration.
        You can create any tqdm or TqdmStats instance and pass the object.

        Parameters
        ----------
        tqdm_object: tqdm, optional
                     A tqdm object will be displayed.
                     if not given, an empty TqdmStats will be created.


        Notes
        --------
        See `joblib.Parallel.__init__` for other parameters.
        """
        self.tqdm_object = tqdm_object
        # set the process of the tqdm instance so that it can calculate
        # the correct statistics based on this process
        tqdm_object.process = Process()
        if self.tqdm_object is None:
            self.tqdm_object = TqdmStats()
        super().__init__(*args, **kwargs)

    def print_progress(self):
        if hasattr(self, "tqdm_object"):
            self.tqdm_object.total = self.n_dispatched_tasks
            self.tqdm_object.n = self.n_completed_tasks
            if self.tqdm_object.total > self.tqdm_object.n:
                self.tqdm_object.update()
                self.tqdm_object.refresh()
)
  ```
when I run a test case that runs this code using ` pytest ./ar_test.py` : 
```python
tqdm_instance = TqdmStats(desc="Fit/Predict the result for each partition...", total=len(part_iter_fit))
all_forecasts_as_series = ParallelTqdm(tqdm_object=tqdm_instance, n_jobs=n_jobs)(
    delayed(self._fit_predict_partition)(part_fit, part_predict, ts_meta) for part_fit, part_predict in zip(part_iter_fit, part_iter_predict))
```

It passed all the test cases and give this exception to the end:
```python
Exception ignored in: <function tqdm.__del__ at 0x7f5ccbae8d30>
Traceback (most recent call last):
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/tqdm/std.py", line 1077, in __del__
    self.close()
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/tqdm/std.py", line 1260, in close
    self._decr_instances(self)
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/tqdm/std.py", line 558, in _decr_instances
    inst.clear(nolock=True)
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/tqdm/std.py", line 1300, in clear
    self.moveto(pos)
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/tqdm/std.py", line 1417, in moveto
    self.fp.write(_unicode('\n' * n + _term_move_up() * -n))
ValueError: I/O operation on closed file.
```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by quancore** [comment]
Any update on this?

**Comment by casperdcl** [comment]
The "error" starts with

> Exception ignored

So it's not actually an error. It's just cleanup at the end of execution and can be ignored.

**Comment by quancore** [comment]
@casperdcl yes you are right but the problem is that this message is keeps printing for our whole data pipeline and messing the log outputs. How can I disable printing or catching this exception?
