### ISSUE TITLE
Cannot set the float digit number

### ISSUE THREAD

**Issue by q-wertz** [tqdm/tqdm#1250]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
  -> 
   ```
   4.62.3 3.9.5 (default, May 11 2021, 08:20:37)
   ```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

The following error is thrown when trying to modify the printed number of digits of a float
```text
Traceback (most recent call last):
  File "/home/user/Desktop/example.py", line 5, in <module>
    with tqdm.tqdm(total=10.1, bar_format="{l_bar}{bar}| {n_fmt:.1f}/{total_fmt:.1f} [{elapsed}<{remaining}, ' '{rate_fmt}{postfix}]") as tpbar:
  File "/home/user/VCS/ads-b_simulator/.venv/lib/python3.9/site-packages/tqdm/std.py", line 1109, in __init__
    self.refresh(lock_args=self.lock_args)
  File "/home/user/VCS/ads-b_simulator/.venv/lib/python3.9/site-packages/tqdm/std.py", line 1346, in refresh
    self.display()
  File "/home/user/VCS/ads-b_simulator/.venv/lib/python3.9/site-packages/tqdm/std.py", line 1494, in display
    self.sp(self.__str__() if msg is None else msg)
  File "/home/user/VCS/ads-b_simulator/.venv/lib/python3.9/site-packages/tqdm/std.py", line 1150, in __str__
    return self.format_meter(**self.format_dict)
  File "/home/user/VCS/ads-b_simulator/.venv/lib/python3.9/site-packages/tqdm/std.py", line 524, in format_meter
    nobar = bar_format.format(bar=full_bar, **format_dict)
ValueError: Unknown format code 'f' for object of type 'str'
Exception ignored in: <function tqdm.__del__ at 0x7ff408dd6e50>
Traceback (most recent call last):
  File "/home/user/VCS/ads-b_simulator/.venv/lib/python3.9/site-packages/tqdm/std.py", line 1147, in __del__
    self.close()
  File "/home/user/VCS/ads-b_simulator/.venv/lib/python3.9/site-packages/tqdm/std.py", line 1276, in close
    if self.last_print_t < self.start_t + self.delay:
AttributeError: 'tqdm' object has no attribute 'last_print_t'
```
might be related to https://github.com/tqdm/tqdm/issues/261.

The minimum code example `example.py`:
```python
import tqdm
import time

with tqdm.tqdm(total=10.1, bar_format="{l_bar}{bar}| {n_fmt:.1f}/{total_fmt:.1f} [{elapsed}<{remaining}, ' '{rate_fmt}{postfix}]") as tpbar:
    for _ in range(10):
        time.sleep(0.1)
        tpbar.update(1.0)
```
When removing both `:.1f` the code works fine.

**Comment by psmaragdis** [comment]
It would be great to have this work with rate as well, especially when having large numbers it is useful to be able to add thousands commas or remove decimals.
