### ISSUE TITLE
pytest-asyncio DeprecationWarning regarding migration of `asyncio_mode` default value

### ISSUE THREAD

**Issue by mweinelt** [tqdm/tqdm#1289]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  - NixOS 22.05 (unstable)
  - Python 3.9.10
  - tqdm 4.62.3
  - pytest 6.2.5
  - pytest-asyncio 0.17.0
 
[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

With the pytest-asyncio upgrade to 0.17.0 (https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.17.0) we're seeing the test suite fail with a DeprecationWarning.

```py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/nix/store/4jkpympg0q96d3pz8pas80mr13w5jkv7-python3.9-pytest-6.2.5/lib/python3.9/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/nix/store/4jkpympg0q96d3pz8pas80mr13w5jkv7-python3.9-pytest-6.2.5/lib/python3.9/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/nix/store/54w5nwd2bhak3324ccg0inc1darcsjlm-python3.9-pytest-asyncio-0.17.0/lib/python3.9/site-packages/pytest_asyncio/plugin.py", line 112, in pytest_configure
INTERNALERROR>     config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
INTERNALERROR>   File "/nix/store/4jkpympg0q96d3pz8pas80mr13w5jkv7-python3.9-pytest-6.2.5/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1321, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
```

We temporarily test tqdm downstream with `--asyncio-mode=strict`, which makes the test suite pass.

**Comment by casperdcl** [comment]
This was fixed in [v4.63.0](https://tqdm.github.io/releases/#v4630-2022-02-28) by #1302
