### ISSUE TITLE
`TypeError` raised if not calling close on object created with `dynamic_ncols=True`

### ISSUE THREAD

**Issue by joshinils** [tqdm/tqdm#1303]
- [x] exception-raising bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
```
4.60.0 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] linux
```

```python
tqdm.tqdm(dynamic_ncols=True)  # ok
tqdm.tqdm()  # ok
foo = tqdm.tqdm()  # ok

pbar = tqdm.tqdm(dynamic_ncols=True)  # TypeError: cannot unpack non-iterable NoneType object
```
But the exception seems to only be raised after pbar is going out of scope at the end of the file, any prints after run just fine.
```
0it [00:00, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7fd72bcbd430>
Traceback (most recent call last):
  File "/home/niels/.local/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
  File "/home/niels/.local/lib/python3.8/site-packages/tqdm/std.py", line 1299, in close
  File "/home/niels/.local/lib/python3.8/site-packages/tqdm/std.py", line 1492, in display
  File "/home/niels/.local/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __str__
  File "/home/niels/.local/lib/python3.8/site-packages/tqdm/std.py", line 1450, in format_dict
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by casperdcl** [comment]
"Exception ignored in" are ignorable warnings that happen at the end of a program if - as you note - you don't properly close things. Probably not a major concern?

Also related: #548
