### ISSUE TITLE
bar_format typeerror for {rate:.3f} format

### ISSUE THREAD

**Issue by ZX1209** [tqdm/tqdm#1438]
## my code
```py
from tqdm.auto import tqdm , trange
# from tqdm.notebook import tqdm
from time import sleep

with tqdm(total=10, 
        desc="desc", bar_format="[{desc}: {percentage:3.0f}%] |{bar}| [{n_fmt}/{total_fmt}] [{elapsed}<<{remaining}] [{rate:.3f} {unit}/s] "
        ) as t:
    for i in range(10):
        sleep(0.1)
        t.update()
```

## env
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
4.64.0 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] win32

## traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\programs\python\python39\lib\site-packages\tqdm\std.py", line 1109, in __init__
    self.refresh(lock_args=self.lock_args)
  File "D:\programs\python\python39\lib\site-packages\tqdm\std.py", line 1361, in refresh
    self.display()
  File "D:\programs\python\python39\lib\site-packages\tqdm\std.py", line 1509, in display
    self.sp(self.__str__() if msg is None else msg)        
  File "D:\programs\python\python39\lib\site-packages\tqdm\std.py", line 1165, in __str__
    return self.format_meter(**self.format_dict)
  File "D:\programs\python\python39\lib\site-packages\tqdm\std.py", line 524, in format_meter
    nobar = bar_format.format(bar=full_bar, **format_dict) 
TypeError: unsupported format string passed to NoneType.__format__

## other
just use rate is ok

- [*] I have marked all applicable categories:
    + [*] exception-raising bug
    + [ ] visual output bug
- [*] I have visited the [source website], and in particular
  read the [known issues]
- [*] I have searched through the [issue tracker] for duplicates
- [*] I have mentioned version numbers, operating system and

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by Ian-Costa18** [comment]
Having the same issue, any updates?
