### ISSUE TITLE
With latest ipywidgets and IPython, get AttributeError: 'tqdm_notebook' object has no attribute 'disp'

### ISSUE THREAD

**Issue by tswast** [tqdm/tqdm#1453]
```
nox > python -m pip freeze
...
ipython==8.11.0
ipywidgets==8.0.5
jedi==0.18.2
jupyterlab-widgets==3.0.6
matplotlib-inline==0.1.6
...
tqdm==4.65.0
...
widgetsnbextension==4.0.6
...
```

```
ests/unit/test_magics.py .F.Exception ignored in: <function tqdm.__del__ at 0x7fd8d74455e0>
Traceback (most recent call last):
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
F...............................FException ignored in: <function tqdm.__del__ at 0x7fd8d74455e0>
Traceback (most recent call last):
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
FException ignored in: <function tqdm.__del__ at 0x7fd8d74455e0>
Traceback (most recent call last):
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
FException ignored in: <function tqdm.__del__ at 0x7fd8d74455e0>
Traceback (most recent call last):
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
F....... [ 48%]
```

**Comment by tswast** [comment]
Also:

```
_____________________ test_context_with_default_connection _____________________

self = <ipywidgets.widgets.trait_types.InstanceDict object at 0x7fe3e9e720d0>
obj = <[ModuleNotFoundError("No module named 'ipykernel'") raised in repr()] FloatProgress object at 0x7fe3e3a4a150>
cls = <class 'ipywidgets.widgets.widget_float.FloatProgress'>

    def get(self, obj, cls=None):
        try:
>           value = obj._trait_values[self.name]
E           KeyError: 'layout'

.nox/prerelease_deps-3-11/lib/python3.11/site-packages/traitlets/traitlets.py:656: KeyError

During handling of the above exception, another exception occurred:
```

**Comment by tswast** [comment]
On second thought, this might not be an issue with tqdm itself?

Looking at https://github.com/jupyter-widgets/ipywidgets/pull/3533 -- looks like a dependency on ipykernel was removed even though we still need it?
