### ISSUE TITLE
tqdm on a list of objects throwing "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte"

### ISSUE THREAD

**Issue by anibal2j** [tqdm/tqdm#1456]
- [X] I have marked all applicable categories:
    + [X] exception-raising bug
    + [ ] visual output bug
- [X] I have visited the [github.com], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

Version information:

```
4.64.1 3.9.16 (main, Dec 23 2022, 17:02:40)
[Clang 14.0.0 (clang-1400.0.29.202)] darwin

```

 I have a list of objects. These objects get initialized from data that's stored in a postgresql DB via psycopg2. I have tried setting the encoding to latin-1 and also to ISO-8859-1 with no effect.

When I execute the line:

```
        dictation_records = dictation_records if self.quiet else tqdm(dictation_records)
```

there's this exception shown on the screen but execution of the script continues:

```
INFO [2023-03-26 13:53:05,014]: Now finding their corresponding order information.
  0%|          | 0/510 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tokenize.py", line 330, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tokenize.py", line 371, in detect_encoding
    encoding = find_cookie(first)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for '/Users/anibal/PycharmProjects/VMG/venv/bin/Python'
python-BaseException
```

**Comment by Danny5487401** [comment]
any update?
