### ISSUE TITLE
Error enabling progress bar

### ISSUE THREAD

**Issue by tomers** [tqdm/tqdm#1531]
```
>>> print(tqdm.__version__, sys.version, sys.platform)
4.64.0 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] linux
```

```
def test():
    with tqdm(disable=True) as t:
        t.total = 100
        t.disable = False
        t.update(1)
```
Result:
```
test.py:78: TqdmWarning: AttributeError ignored
  with tqdm(disable=True) as t:
Traceback (most recent call last):
  File "test.py", line 85, in <module>
    test()
  File "test.py", line 81, in test
    t.update(1)
  File "/home/user/.local/lib/python3.10/site-packages/tqdm/std.py", line 1246, in update
    if self.n - self.last_print_n >= self.miniters:
AttributeError: 'tqdm' object has no attribute 'last_print_n'
```

**Comment by g-abilio** [comment]
@tomers, as the tqdm printing scheme is disabled in it's initialization (by calling disable = True), trying to enable the progress bar wrapper after it was already setted up to not printing it, can generate this problems. tqdm_asyncio, the [Asynchronous progressbar decorator for iterators](https://tqdm.github.io/docs/asyncio/), may not be able to handle printing after it was initialized to non printing.
