### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'last_print_t' on Python 3.12

### ISSUE THREAD

**Issue by mweinelt** [tqdm/tqdm#1537]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

### Environment

Python 3.12.1
pytest 7.4.3
pytest-asyncio 0.23.2
pluggy 1.3.0
tqdm 4.66.1

### Description

I'm aware Python 3.12 is not supported according to the trove classifiers, but I hope it will be soon. We're seeing the following exception many times during testing on Python 3.12.1, the tests run fine on 3.11.7.

```pytb
Exception ignored in: <function tqdm.__del__ at 0x7ffff64a2c00>
Traceback (most recent call last):
  File "/build/tqdm-4.66.1/tqdm/std.py", line 1149, in __del__
    self.close()
  File "/build/tqdm-4.66.1/tqdm/std.py", line 1278, in close
    if self.last_print_t < self.start_t + self.delay:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'tqdm' object has no attribute 'last_print_t'
```

**Comment by stanislavkozlovski** [comment]
I'm hitting this with Python **3.11.8** and latest tqdm **4.66.5**

**Comment by maurerle** [comment]
We were hitting this in a setting on windows where an error happened when creating the `tqdm` as the stderr stream was redirected to something else.

As an error was thrown, it did not fully initialize, throwing this error.

Something like this example will throw the error on windows for example:
```python
@contextlib.contextmanager
def suppress_output():
    # Save the original stdout and stderr file descriptors
    original_stdout_fd = sys.stdout.fileno()
    original_stderr_fd = sys.stderr.fileno()

    # Open /dev/null for redirecting output
    devnull = os.open(os.devnull, os.O_WRONLY)

    # Duplicate the original stdout and stderr file descriptors to restore them later
    saved_stdout_fd = os.dup(original_stdout_fd)
    saved_stderr_fd = os.dup(original_stderr_fd)

    try:
        # Redirect stdout and stderr to /dev/null
        os.dup2(devnull, original_stdout_fd)
        os.dup2(devnull, original_stderr_fd)

        yield  # Allow the block of code to execute

    finally:
        # Restore stdout and stderr from the saved file descriptors
        os.dup2(saved_stdout_fd, original_stdout_fd)
        os.dup2(saved_stderr_fd, original_stderr_fd)

        # Close the duplicated file descriptors and /dev/null
        os.close(saved_stdout_fd)
        os.close(saved_stderr_fd)
        os.close(devnull)

@suppress_output
def test():
    i = 0
    for i in tqdm(range(10)):
        t += 1
```
