### ISSUE TITLE
4.67.0: pytest fails with `Unknown config option: asyncio_default_fixture_loop_scope`

### ISSUE THREAD

**Issue by kloczek** [tqdm/tqdm#1630]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:

I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using `installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

<details>
<summary>Here is pytest output:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-tqdm-4.67.0-2.fc37.x86_64/usr/lib64/python3.10/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-tqdm-4.67.0-2.fc37.x86_64/usr/lib/python3.10/site-packages
+ /usr/bin/pytest -ra -m 'not network' -q --deselect tests/tests_perf.py::test_lock_args
============================= test session starts ==============================
platform linux -- Python 3.10.14, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0
configfile: pyproject.toml
testpaths: tests
plugins: asyncio-0.23.8, timeout-2.3.1
asyncio: mode=strict
timeout: 30.0s
timeout method: signal
timeout func_only: False
collected 150 items / 1 deselected / 149 selected
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/main.py", line 292, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/main.py", line 345, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/logging.py", line 794, in pytest_collection
INTERNALERROR>     return (yield)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/warnings.py", line 120, in pytest_collection
INTERNALERROR>     return (yield)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 124, in _multicall
INTERNALERROR>     teardown.send(result)  # type: ignore[union-attr]
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1425, in pytest_collection
INTERNALERROR>     self._validate_config_options()
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1447, in _validate_config_options
INTERNALERROR>     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1486, in _warn_or_fail_if_strict
INTERNALERROR>     self.issue_config_time_warning(PytestConfigWarning(message), stacklevel=3)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1538, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: asyncio_default_fixture_loop_scope

============================ 1 deselected in 0.76s =============================
```
</details>

<details>
<summary>List of installed modules in build env:</summary>

```console
Package            Version
------------------ -----------
build              1.2.2.post1
click              8.1.7
cloudpickle        3.1.0
dask               2024.6.2
distro             1.9.0
exceptiongroup     1.1.3
fsspec             2024.10.0
importlib_metadata 8.5.0
iniconfig          2.0.0
installer          0.7.0
locket             1.0.0
markdown-it-py     3.0.0
mdurl              0.1.2
numpy              1.26.4
packaging          24.0
pandas             2.2.1
partd              1.4.1
pluggy             1.5.0
Pygments           2.18.0
pyproject_hooks    1.2.0
pytest             8.2.2
pytest-asyncio     0.23.8
pytest-timeout     2.3.1
python-dateutil    2.9.0.post0
pytz               2024.2
PyYAML             6.0.2
rich               13.7.1
setuptools         75.1.0
setuptools-scm     8.1.0
tokenize_rt        6.1.0
tomli              2.0.1
toolz              1.0.0
wheel              0.44.0
zipp               3.20.2
```
</details>

Please let me know if you need more details or want me to perform some diagnostics.

**Comment by maurerle** [comment]
You need to install `pytest-asyncio` for this to work.
This is not a problem of tqdm.

See also: https://github.com/pytest-dev/pytest-asyncio/issues/924

**Comment by kloczek** [comment]
From list of modules installed in build env:
```console
pytest-asyncio     0.23.8
```

**Comment by casperdcl** [comment]
#1627 (v4.66.6) fixed a `DeprecationWarning` by requring `pytest-asyncio>0.21` (which requires `python>=3.8`)

**Comment by maurerle** [comment]
@kloczek has python 3.10, pytest=8.2.2 and pytest-asyncio=0.23.8. So that has nothing to do with the mentioned pr by @casperdcl 

Instead, the https://github.com/pytest-dev/pytest-asyncio/issues/924 requires to have at least `pytest-asyncio>=0.24.0`

**Comment by casperdcl** [comment]
Ah looks like we may need to drop `asyncio_default_fixture_loop_scope` and instead require `pytest-asyncio!=0.22.*,!=0.23.*`

**Comment by kloczek** [comment]
> Ah looks like we may need to drop asyncio_default_fixture_loop_scope and instead require pytest-asyncio!=0.22.*,!=0.23.*

Or require `pytest-asyncio>=0.24`.

Just tested with `pytest-asyncio>=0.24.0` and pytest is able to start but it fails in one unit
<details>
<summary>Here is pytest output:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-tqdm-4.67.0-2.fc37.x86_64/usr/lib64/python3.10/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-tqdm-4.67.0-2.fc37.x86_64/usr/lib/python3.10/site-packages
+ /usr/bin/pytest -ra -m 'not network' -q
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.10.14, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0
configfile: pyproject.toml
testpaths: tests
plugins: hypothesis-6.100.0, datadir-1.5.0, regressions-2.5.0, trio-0.8.0, flaky-3.8.1, timeout-2.3.1, asyncio-0.24.0
timeout: 30.0s
timeout method: signal
timeout func_only: False
asyncio: mode=strict, default_loop_scope=function
collected 150 items

tests/tests_asyncio.py .......                                                                                                                                                        [  4%]
tests/tests_concurrent.py ........                                                                                                                                                    [ 10%]
tests/tests_contrib.py .......                                                                                                                                                        [ 14%]
tests/tests_contrib_logging.py ..................                                                                                                                                     [ 26%]
tests/tests_dask.py .                                                                                                                                                                 [ 27%]
tests/tests_gui.py .                                                                                                                                                                  [ 28%]
tests/tests_itertools.py .                                                                                                                                                            [ 28%]
tests/tests_keras.py s                                                                                                                                                                [ 29%]
tests/tests_main.py ........                                                                                                                                                          [ 34%]
tests/tests_notebook.py .                                                                                                                                                             [ 35%]
tests/tests_pandas.py ........                                                                                                                                                        [ 40%]
tests/tests_perf.py ..F....                                                                                                                                                                                 [ 45%]
tests/tests_rich.py .                                                                                                                                                                 [ 46%]
tests/tests_synchronisation.py .....                                                                                                                                                  [ 49%]
tests/tests_tk.py .                                                                                                                                                                   [ 50%]
tests/tests_tqdm.py .......................................................................                                                                                           [ 97%]
tests/tests_utils.py ...                                                                                                                                                              [ 99%]
tests/tests_version.py .                                                                                                                                                              [100%]

========================================================================================= FAILURES ==========================================================================================
______________________________________________________________________________________ test_lock_args _______________________________________________________________________________________
tests/tests_perf.py:216: in test_lock_args
    res = list(pool.map(worker(subtotal, True), range(total)))
/usr/lib64/python3.10/concurrent/futures/_base.py:621: in result_iterator
    yield _result_or_cancel(fs.pop())
/usr/lib64/python3.10/concurrent/futures/_base.py:319: in _result_or_cancel
    return fut.result(timeout)
/usr/lib64/python3.10/concurrent/futures/_base.py:453: in result
    self._condition.wait(timeout)
/usr/lib64/python3.10/threading.py:320: in wait
    waiter.acquire()
E   Failed: Timeout >30.0s
----------------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------------------
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_15 (140159043503808) ~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_14 (140159053989568) ~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tests/tests_perf.py", line 196, in incr_bar
    for _ in trange(total, lock_args=None if blocking else (False,),
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1191, in __iter__
    self.update(n - last_print_n)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1242, in update
    self.refresh(lock_args=self.lock_args)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1346, in refresh
    self._lock.acquire()
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_13 (140159064475328) ~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tests/tests_perf.py", line 196, in incr_bar
    for _ in trange(total, lock_args=None if blocking else (False,),
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1191, in __iter__
    self.update(n - last_print_n)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1242, in update
    self.refresh(lock_args=self.lock_args)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1346, in refresh
    self._lock.acquire()
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_12 (140159074961088) ~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_11 (140159223858880) ~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_10 (140159234344640) ~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tests/tests_perf.py", line 196, in incr_bar
    for _ in trange(total, lock_args=None if blocking else (False,),
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1191, in __iter__
    self.update(n - last_print_n)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1263, in update
    return True
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1350, in refresh
    return True
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_9 (140159244830400) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tests/tests_perf.py", line 196, in incr_bar
    for _ in trange(total, lock_args=None if blocking else (False,),
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1191, in __iter__
    self.update(n - last_print_n)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1263, in update
    return True
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1350, in refresh
    return True
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1498, in display
    return True
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1444, in moveto
    getattr(self.fp, 'flush', lambda: None)()
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/utils.py", line 196, in inner
    return func(*args, **kwargs)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_8 (140159255316160) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tests/tests_perf.py", line 196, in incr_bar
    for _ in trange(total, lock_args=None if blocking else (False,),
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1191, in __iter__
    self.update(n - last_print_n)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1263, in update
    return True
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1350, in refresh
    return True
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_7 (140159265801920) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_6 (140159276287680) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tests/tests_perf.py", line 196, in incr_bar
    for _ in trange(total, lock_args=None if blocking else (False,),
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1191, in __iter__
    self.update(n - last_print_n)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1242, in update
    self.refresh(lock_args=self.lock_args)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1346, in refresh
    self._lock.acquire()
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_5 (140159423088320) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_4 (140159433574080) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tests/tests_perf.py", line 196, in incr_bar
    for _ in trange(total, lock_args=None if blocking else (False,),
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1191, in __iter__
    self.update(n - last_print_n)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1242, in update
    self.refresh(lock_args=self.lock_args)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1346, in refresh
    self._lock.acquire()
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_3 (140159444059840) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_2 (140159454545600) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_1 (140159465031360) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tests/tests_perf.py", line 196, in incr_bar
    for _ in trange(total, lock_args=None if blocking else (False,),
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1191, in __iter__
    self.update(n - last_print_n)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1242, in update
    self.refresh(lock_args=self.lock_args)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1346, in refresh
    self._lock.acquire()
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-3_0 (140159559403200) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tests/tests_perf.py", line 196, in incr_bar
    for _ in trange(total, lock_args=None if blocking else (False,),
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1191, in __iter__
    self.update(n - last_print_n)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1242, in update
    self.refresh(lock_args=self.lock_args)
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/std.py", line 1346, in refresh
    self._lock.acquire()
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-2_3 (140159569888960) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-2_2 (140159580374720) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-2_1 (140159590860480) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~ Stack of ThreadPoolExecutor-2_0 (140159601346240) ~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-3 (140159611832000) ~~~~~~~~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/_monitor.py", line 60, in run
    self.was_killed.wait(self.sleep_interval)
  File "/usr/lib64/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib64/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-1 (140159699912384) ~~~~~~~~~~~~~~~~~~~~~~
  File "/usr/lib64/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tkloczko/rpmbuild/BUILD/tqdm-4.67.0/tqdm/_monitor.py", line 60, in run
    self.was_killed.wait(self.sleep_interval)
  File "/usr/lib64/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib64/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
----------------------------------------------------------------------------------- Captured stderr call ------------------------------------------------------------------------------------
100%|██████████| 10000/10000 [00:14<00:00, 684.72it/s]
100%|██████████| 10000/10000 [00:16<00:00, 603.37it/s]
100%|██████████| 10000/10000 [00:20<00:00, 487.88it/s]
100%|██████████| 10000/10000 [00:22<00:00, 438.56it/s]
100%|██████████| 10000/10000 [00:23<00:00, 426.28it/s]
100%|██████████| 10000/10000 [00:24<00:00, 406.21it/s]
100%|██████████| 10000/10000 [00:25<00:00, 386.19it/s]
100%|██████████| 10000/10000 [00:30<00:00, 325.25it/s]
100%|██████████| 10000/10000 [00:31<00:00, 320.09it/s]
100%|██████████| 10000/10000 [00:31<00:00, 312.53it/s]
100%|██████████| 10000/10000 [00:32<00:00, 303.23it/s]]
100%|██████████| 10000/10000 [00:34<00:00, 290.07it/s]]
100%|██████████| 10000/10000 [00:34<00:00, 286.19it/s]
100%|██████████| 10000/10000 [00:35<00:00, 285.09it/s]
100%|██████████| 10000/10000 [00:35<00:00, 277.89it/s]
100%|██████████| 10000/10000 [00:36<00:00, 277.52it/s] ]
===================================================================================== slowest durations =====================================================================================
36.13s call     tests/tests_perf.py::test_lock_args/s]
5.70s call     tests/tests_perf.py::test_iter_overhead_hard
5.59s call     tests/tests_perf.py::test_manual_overhead_hard
2.95s call     tests/tests_perf.py::test_iter_basic_overhead
2.75s call     tests/tests_perf.py::test_manual_basic_overhead
0.91s call     tests/tests_asyncio.py::test_as_completed[0.1]
0.61s call     tests/tests_perf.py::test_iter_overhead_simplebar_hard
0.60s call     tests/tests_perf.py::test_manual_overhead_simplebar_hard
0.50s call     tests/tests_dask.py::test_dask5.18it/s]
0.43s call     tests/tests_pandas.py::test_pandas_data_frame
0.34s call     tests/tests_tqdm.py::test_rlock_creation
0.29s call     tests/tests_synchronisation.py::test_imap
0.17s call     tests/tests_main.py::test_pipes
0.16s call     tests/tests_concurrent.py::test_process_map

(436 durations < 0.1s hidden.  Use -vv to show these durations.)
================================================================================== short test summary info ==================================================================================
SKIPPED [1] tests/tests_keras.py:9: could not import 'tqdm.keras': No module named 'keras'
FAILED tests/tests_perf.py::test_lock_args - Failed: Timeout >30.0s
==================================================================== 1 failed, 148 passed, 1 skipped in 62.70s (0:01:02) ====================================================================
```
</details>
