### ISSUE TITLE
I/O operation on closed file bug

### ISSUE THREAD

**Issue by pauljherrera** [tqdm/tqdm#202]
Eighty percent of the time I use tqdm it works perfectly. The other 20%  I get 'I/O operation on closed file'.

The weird thing about it is that I can use tqdm in the same script two times. The first time it doesn't work. The second time, without changing anything , it works.

I paste below the complete traceback:

```
File "<ipython-input-160-51605e3202c6>", line 1, in <module>
    runfile('C:/Users/forex/Documents/Knoxpy simple/Avanti_Analyzer.py', wdir='C:/Users/forex/Documents/Knoxpy simple')

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/forex/Documents/Knoxpy simple/Avanti_Analyzer.py", line 1114, in <module>
    barsperday, commission, swap, join, verbose = True)

  File "C:/Users/forex/Documents/Knoxpy simple/Avanti_Analyzer.py", line 1022, in w_eventstudy
    df = overlaps(df, overlapperiod, signal, trigger)

  File "C:/Users/forex/Documents/Knoxpy simple/Avanti_Analyzer.py", line 438, in overlaps
    for i in tqdm(xrange(overlapperiod - 1, len(x1))):

  File "C:\Anaconda2\lib\site-packages\tqdm\_tqdm.py", line 622, in __iter__
    else ncols),

  File "C:\Anaconda2\lib\site-packages\tqdm\_tqdm.py", line 98, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))

  File "C:\Anaconda2\lib\site-packages\tqdm\_tqdm.py", line 92, in fp_write
    fp_flush()

  File "C:\Anaconda2\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)

  File "C:\Anaconda2\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)

  File "C:\Anaconda2\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))

  File "C:\Anaconda2\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])

  File "C:\Anaconda2\lib\site-packages\ipykernel\iostream.py", line 317, in write
    self._buffer.write(string)

ValueError: I/O operation on closed file
```

**Comment by lrq3000** [comment]
That's a really weird error. I can't guess why there is an IO error since `tqdm` streams to the console normally. But it seems `colorama` might be at fault here.

Could you please try to uninstall `colorama` and retry your script several times in order to see if the error happens again? (you will need to restart your ipython notebook kernel before to force the reloading of modules).

If this still produces an IO error randomly, could you please give us the script (or better a minimal example)?

**Comment by jveitchmichaelis** [comment]
Here is code that fails for me. The function takes a list of images from two cameras and stacks them together to produce one output image.

```
import numpy as np
from tqdm import tqdm
import cv2

def stack_images(l, r):
    lim = cv2.imread(l[0], cv2.IMREAD_GRAYSCALE)
    rim = cv2.imread(r[0], cv2.IMREAD_GRAYSCALE)
    
    for l_i, r_i in tqdm(zip(l[1:],r[1:])):
            lim_new = cv2.imread(l_i, cv2.IMREAD_GRAYSCALE)
            if lim_new is None:
                raise IOError
            lim = np.maximum(lim, lim_new)
            rim_new = cv2.imread(r_i, cv2.IMREAD_GRAYSCALE)
            if rim_new is None:
                raise IOError
            rim = np.maximum(rim, rim_new)
    return lim, rim
```

**Comment by samuelleach** [comment]
Just to note that I have observed the same occasional `ValueError`. It is hard to reproduce. Maybe the following is helpful: python 2.7. Error occurred after approx 400K iteration of a 15 minute job.

**Comment by casperdcl** [comment]
This is... frustrating. I don't want to say this, but... bug in python?

**Comment by casperdcl** [comment]
@jveitchmichaelis maybe you need an extra wait?
``` python
import numpy as np
from tqdm import tqdm
import cv2
import time.sleep

def stack_images(r):
    rim = cv2.imread(r[0], cv2.IMREAD_GRAYSCALE)
    for r_i in tqdm(r[1:]):
            rim_new = cv2.imread(r_i, cv2.IMREAD_GRAYSCALE)
            if rim_new is None:
                raise IOError
            rim = np.maximum(rim, rim_new)
    time.sleep(1)  # wait for possible io to fininsh?
    return rim

# ...

import glob
left_ims = glob.glob('./left_*.png')
right_ims = glob.glob('./right_*.png')

# ensure same length
left_ims = left_ims[:min(len(left_ims), len(right_ims))]
right_ims = right_ims[:len(left_ims)]

# stack
left_stack = stack_images(left_ims)
right_stack = stack_images(right_ims)
```

**Comment by jveitchmichaelis** [comment]
I'll try that, although I have around 30-40k images to process so it might take a while (I guess 1s was for demonstration rather than anything else). Typically this thing runs at around 40 iterations per second and there isn't a problem when `tqdm` isn't used.

There was a reason I read in both images in the same function, but I forget why (I think previously I was doing a joint operation on them as I read them in) :)

**Comment by casperdcl** [comment]
My reasoning about the 1 second wait was that maybe your entire program is ending just before all of the file handles are properly closed or something. It's just a  wait right at the end of the program.

**Comment by jveitchmichaelis** [comment]
Ah sorry misread that! But it fails mid-sequence, not at the end.

**Comment by gcr** [comment]
I have this bug too and it's frustrating. It only began very recently (within the last week); tqdm was rock-solid before that.

In a long-running task, sometimes tqdm throws an exception 30% of the way in. It doesn't just happen at the end.

(I'm using tqdm inside an IPython Notebook. Will report back with a traceback if it's separate from above.)

**Comment by gcr** [comment]
My traceback appears in the same place, but it also happens on Linux:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

/home/gcr/share/behance/mturk-tools/incremental_learning.pyc in load(mids)
     36         return np.array([
     37             h5_features[mid_to_idx[mid]]
---> 38             for mid in tqdm(list(mids))
     39         ])
     40     return load

/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.pyc in __iter__(self)
    620                              else ncols),
    621                             self.desc, ascii, unit, unit_scale,
--> 622                             1 / avg_time if avg_time else None, bar_format))
    623 
    624                         if self.pos:

/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.pyc in print_status(s)
     96         def print_status(s):
     97             len_s = len(s)
---> 98             fp_write('\r' + s + (' ' * max(last_printed_len[0] - len_s, 0)))
     99             fp.flush()
    100             last_printed_len[0] = len_s

/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.pyc in fp_write(s)
     90 
     91         def fp_write(s):
---> 92             fp.write(_unicode(s))
     93 
     94         last_printed_len = [0]  # closure over mutable variable (fast)

/usr/local/lib/python2.7/dist-packages/ipykernel/iostream.pyc in write(self, string)
    315 
    316             is_child = (not self._is_master_process())
--> 317             self._buffer.write(string)
    318             if is_child:
    319                 # newlines imply flush in subprocesses

ValueError: I/O operation on closed file
```

**Comment by casperdcl** [comment]
When you say only in the last week, do you mean you regularly update your
python packages? What was the last tqdm version which was stable for you?
When you get the error, is it always at 30% through that loop, or sometimes
earlier/later?

An easy fix for now would be for me to catch the exception internally and
ignore it, but I'd still like to get to the real cause.

**Comment by gcr** [comment]
Pardon. I rarely update python packages, so I don't think they changed from then until now.

However, one confusing factor could be that this week I am doing longer-running tasks. The total output produced by tqdm is much larger than it was before. That's one difference. Maybe it could be overflowing some internal buffer? (Is there a way to measure the amount of raw output that tqdm produces?)

tqdm doesn't always throw in the same place though. Sometimes the progress bar completes; sometimes it stops at 50%. It _usually_ works.

**Comment by casperdcl** [comment]
thanks.

can anyone confirm this is still a bug using tqdm>=4.7.5?

**Comment by gcr** [comment]
aha! i'm still seeing this behavior occasionally on 4.8.1-b71261d. i didn't save a traceback (foolish me!), will post one if i see it again.

**Comment by gcr** [comment]
here's a traceback. seems similar to last time. do i need to install from git or is `4.8.1-b71261d` okay?

```pthon
-----------------------------------------------------------------
ValueError                      Traceback (most recent call last)
<ipython-input-15-8dbf7217f681> in <module>()
      1 pid_to_mids = collections.defaultdict(set)
----> 2 for pid,mid in tqdm(cur.execute("select project_id, id from modules")):
      3     pid_to_mids[pid].add(mid)
      4 cache['pid_to_mids'] = {k: list(v) for k,v in pid_to_mids.iteritems()}

/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.pyc in __iter__(self)
    728                              else ncols),
    729                             self.desc, ascii, unit, unit_scale,
--> 730                             1 / avg_time if avg_time else None, bar_format))
    731 
    732                         if self.pos:

/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.pyc in print_status(s)
    115         def print_status(s):
    116             len_s = len(s)
--> 117             fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
    118             last_len[0] = len_s
    119         return print_status

/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.pyc in fp_write(s)
    108 
    109         def fp_write(s):
--> 110             fp.write(_unicode(s))
    111             fp_flush()
    112 

/usr/local/lib/python2.7/dist-packages/ipykernel/iostream.pyc in write(self, string)
    315 
    316             is_child = (not self._is_master_process())
--> 317             self._buffer.write(string)
    318             if is_child:
    319                 # newlines imply flush in subprocesses

ValueError: I/O operation on closed file
```

**Comment by casperdcl** [comment]
unless anyone has any better suggestions, I could catch this error and print a warning to stderr linking to this page in the hope of a fix. Does this only occur with ipython? or only one platform? @lrq3000 what do you think

**Comment by lrq3000** [comment]
Hey there, sorry for the delay. I agree @casperdcl that we really should try to find the culprit and skip the error only as a last resort.
I used tqdm in several tools that process huge amount of files, the best example being [pyFileFixity](https://github.com/lrq3000/pyFileFixity/), and I never had any issue with any amount of files. However, I didn't try with the latest releases of `tqdm`, so maybe a glitch has sneaked somewhere.

Would someone here be willing to provide the scripts producing the issues, so that we can try to reproduce them on our own? We would also need to know how many files and what amount of gigabytes are in total for the files that were processed up until the issue happened.

**Comment by lrq3000** [comment]
It seems the issue's culprit lies is inside ipykernel of IPython. Sometimes, the sys.stdout lock doesn't get released correctly and it seems this produces a race condition.

@goretkin seems to already have traced back the issue a few weeks ago in https://github.com/ipython/ipython/issues/9168.

The solution to this issue seems to either update IPython notebook (because it includes the fix https://github.com/ipython/ipykernel/pull/123) or to disable all outputs from your programs (or redirect to a file) as proposed on the Keras project (https://github.com/fchollet/keras/issues/2110).

So, to summarize:

* This issue seems to happen randomly (an heisenbug!) when you print inside an IPython notebook. The more you print, the more you are likely to encounter this bug. Restarting the notebook kerned should fix the issue temporarily (there's no guarantee you will encounter it again during the rest of the session, and it won't fix anything for the next time you reopen your notebook).

* Fix for `tqdm` users: simply use `tqdm_notebook`, this doesn't produce any stdout output, so it should be safe from this issue (except if you `tqdm_notebook.write()`).

* Fix for `tqdm` devs: we could wrap our printing in a try/catch block and skip the exception silently as @casperdcl suggered, but the side effect is that we may skip legitimate errors in other environments than IPython notebook, and secondly it won't prevent the bug from happening from other modules or user's own code. We could maybe provide an argument `robust=True` that would ensure that `tqdm` will skip absolutely any kind of error, this could indeed be useful for some users in production environments (or when they run algorithms that last several days, we don't want `tqdm` to interrupt even if it's not directly its fault...).

So what do you think about it @casperdcl ? Should we provide a `robust` argument in `tqdm`? Also we should add to the documentation that IPython has a bug that may cause core `tqdm` (and any printing function) to crash the execution, and thus advise to use `tqdm_notebook`.

**Comment by lrq3000** [comment]
PS: I'm not a 100% sure IPython Notebook is the culprit but there are very good reasons to think so:

1. After a careful inspection of core `tqdm` code, I can't see where the sys.stdout would be closed prematurely.
2. The traceback clearly shows that the error is raised by ipykernel.
3. There's no reason ipykernel should prevent sys.stdout to be writeable: sys.stdout is never closeable, so this is clearly a bug.

**Comment by gcr** [comment]
For the record, I've only used tqdm in a Jupyter Notebook. Could be something funny happening with Jupyter's output buffering, for example.

**Comment by lrq3000** [comment]
@gcr: You and @pauljherrera trace show that you were both using IPython Notebook, for the others I cannot be sure because they didn't provide a traceback, but I would be willing to bet they also were. If someone happens to get this issue without using IPython, please post your traceback here, that would be highly helpful!

**Comment by lrq3000** [comment]
Update: the patch that should seemingly fix this issue is not yet committed to IPython public releases, it will be out shortly with IPython v4.4. We should try again then to see if this fixes the issue for good.

**Comment by jveitchmichaelis** [comment]
Yup, mine was in iPython too.

**Comment by lrq3000** [comment]
Thank's for the feedback @jveitchmichaelis :) I just noticed @gcr also
reported the issue happening in IPython notebook, so we have 4 reports
converging towards a bug in IPython.
Le 1 Aoû. 2016 18:08, "jveitchmichaelis" <notifications@github.com> a
écrit :

**Comment by casperdcl** [comment]
yay! tqdm finds more bugs in other people's code...

**Comment by lrq3000** [comment]
Yeah that's bothering and great at the same time, because it means `tqdm` is becoming quite robust now :)

**Comment by samuelleach** [comment]
I have also been getting this issue on Jupyter notebook.

@lrq3000 Would it be possible if you can post the corresponding bug report you mentioned in iPython notebook repo? I'd be glad to know when this issue will be resolved 👍

**Comment by lrq3000** [comment]
@samuelleach The bug report is here: https://github.com/ipython/ipython/issues/9168 and the PR that will supposedly fix the issue by v4.4 here: https://github.com/ipython/ipykernel/pull/123

**Comment by lrq3000** [comment]
Ah the ipykernel v4.4.1 was released on 2016-08-09: https://pypi.python.org/pypi/ipykernel

So we can soon try again this issue (most packages like Anaconda gets updated one month after the pypi release usually).

**Comment by samuelleach** [comment]
Thanks for the info. Anecdotally, based on the last few hours usage of tqdm, things are stable since I did `conda update ipykernel` and got version 4.4.1 👍

**Comment by casperdcl** [comment]
Not a bug with tqdm, bug fixed elsewhere

**Comment by lrq3000** [comment]
At least we hope it's fixed, I did not update ipywidgets so I did not test
it myself. Anyone, please feel free to reopen this issue if the issue
arises again with the latest ipywidgets!

2016-10-19 17:25 GMT+02:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
still, it's nice to know that `tqdm` appears to be more stable that `ipython`, hah

**Comment by Varun-Epi** [comment]
Hey, I am getting this error and am not using jupyter/ipython.  Its quite random, in my earlier experiments tqdm was working perfectly fine, but now this error is recurring in some of the experiments.
```
  File "train-ner.py", line 367, in train
    with tqdm.tqdm(total=n_train_words, leave=False) as pbar:
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 812, in __init__
    self.sp(self.__repr__(elapsed=0))
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 176, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 169, in fp_write
    fp.write(_unicode(s))
IOError: [Errno 32] Broken pipe
```
**Details**
```
Platform : Ubuntu 16.04
tqdm : 4.19.9
```

**Comment by ABCDeath** [comment]
That's realy weird, but I can reproduce this error everytime I _debug_ a Python file like this with PyCharm:
```python
from tqdm import tqdm

if __name__ == '__main__':
    for _ in tqdm(range(10)):
        pass
```
When I _run_ the same file in PyCharm it doesn't throw this exception.
MacOs 10.15.4, Python 3.8.2, tqdm 4.46.0.

**Comment by casperdcl** [comment]
pretty sure this is an upstream bug with PyCharm, would be helpful if someone finds/posts an issue.
