### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'last_print_t'

### ISSUE THREAD

**Issue by chenasraf** [tqdm/tqdm#261]
Didn't use to happen before, not sure why it started happening. I've got 
```
Traceback (most recent call last):
  File "main.py", line 206, in <module>
    OrgbaseQ(**settings).start()
  File "/Users/casraf/Dev/whitespace-tools/item_q/item_q/item_q.py", line 26, in start
  File "main.py", line 125, in flush
    tqdm.write('Found %d matching people by names' % pg_count)
  File "/usr/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 343, in write
    inst.refresh()
  File "/usr/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 944, in refresh
    self.fp.write(self.__repr__())
  File "/usr/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 649, in __repr__
    time() - self.last_print_t,
AttributeError: 'tqdm' object has no attribute 'last_print_t'
```

**Comment by CrazyPython** [comment]
@chenasraf surrounding code?

**Comment by chenasraf** [comment]
```python
            pg_cursor = self.pgdb.cursor()
            pg_query = """
                SELECT id, first_name, last_name, emails #>> '{{0,address}}' AS email, jobs
                FROM people
                WHERE (jobs IS NOT NULL OR emails #>> '0' IS NOT NULL)
                AND ({conditions})
            """.format(conditions=' OR '.join(conditions))
            count = 0

            tqdm.write('Found %d matching people by names' % self._pg_count_query(pg_cursor, pg_query))  # error points here
            pg_cursor.execute(pg_query)
            for person in tqdm(pg_cursor.fetchall(), **self.options['tqdm_defaults']):
                pg_id, first_name, last_name, email, jobs = person
```

I have to point out I have about 2-3 progress bar working alongside each other here, not sure if that has anything to do with it but I'm guessing it does.

**Comment by lrq3000** [comment]
Hello @chenasraf, are the bars working in parallel or sequentially? If they are working in parallel, then you may be running into a racing condition, the write method is indeed not parallel safe. But it may be fixed if that's the issue here.

**Comment by lrq3000** [comment]
@chenasraf If your bars are indeed working in parallel, please try this experimental release and tell us if this fixes your issue:

https://github.com/tqdm/tqdm/archive/small-fix-refresh.zip

Thank's!

**Comment by lrq3000** [comment]
Closed by #264.

**Comment by lrq3000** [comment]
Please reopen if this did not fix your issue.

**Comment by thammegowda** [comment]
Same problem, but I was not using any parallels, 
it was just I had hijacked `sys.stdout.buffer` (to enforce unicode; generally NOT advised to do so unless you know what you are doing)
```python
stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='ignore')
```
and tqdm tried to `sys.stdout.flush()` and crashed!
```
Traceback (most recent call last):
  File ".../rtg/module/decoder.py", line 581, in _decode_all
    with tqdm.tqdm(batches, dynamic_ncols=True, desc='Decoding', unit='segs') as data_bar:
  File "...python3.9/site-packages/tqdm/std.py", line 1107, in __init__
    self.sp = self.status_printer(self.fp)
  File "...python3.9/site-packages/tqdm/std.py", line 340, in status_printer
    sys.stdout.flush()
ValueError: I/O operation on closed file.
Exception ignored in: <function tqdm.__del__ at 0x7f79d58bc3a0>
Traceback (most recent call last):
  File "...python3.9/site-packages/tqdm/std.py", line 1147, in __del__
    self.close()
  File "...python3.9/site-packages/tqdm/std.py", line 1276, in close
    if self.last_print_t < self.start_t + self.delay:
AttributeError: 'tqdm' object has no attribute 'last_print_t'
```

**Comment by JLHasson** [comment]
I was seeing this error in `4.62.3` (didn't check other versions) when running TQDM in a process that was detached from a shell with stderr piped but not stdout. I.e.
```
# in shell that will eventually exit but leave the process running
nohup ./some-process 2> /tmp/file &
```

This resulted in the `logging` module encountering a `BrokenPipeError: [Errno 32] Broken pipe` when the logger tried to flush. Then the error above would occur anytime TQDM tried to run.  The fix was to also pipe stdout somewhere.

**Comment by flacanellas** [comment]
Same error here, version `4.64.0`, used to download file as stream with requests module on `Python 3.8` at `ubuntu 20.04.4`. 

```
Traceback (most recent call last):
  File "./download.py", line 79, in <module>
    main()
  File "./download.py", line 69, in main
    tqdm(desc=fileName, total=fileSize, unit='iB', unit_scale=True, unit_divisor=1024) as bar:
  File "/hidden.../.local/lib/python3.8/site-packages/tqdm/std.py", line 1109, in __init__
    self.refresh(lock_args=self.lock_args)
  File "/hidden.../.local/lib/python3.8/site-packages/tqdm/std.py", line 1361, in refresh
    self.display()
  File "/hidden.../.local/lib/python3.8/site-packages/tqdm/std.py", line 1509, in display
    self.sp(self.__str__() if msg is None else msg)
  File "/hidden.../.local/lib/python3.8/site-packages/tqdm/std.py", line 1165, in __str__
    return self.format_meter(**self.format_dict)
  File "/hidden.../.local/lib/python3.8/site-packages/tqdm/std.py", line 425, in format_meter
    if total and n >= (total + 0.5):  # allow float imprecision (#849)
TypeError: can only concatenate str (not "float") to str
Exception ignored in: <function tqdm.__del__ at 0x7f70fec5fa60>
Traceback (most recent call last):
  File "/hidden.../.local/lib/python3.8/site-packages/tqdm/std.py", line 1162, in __del__
    self.close()
  File "/hidden.../.local/lib/python3.8/site-packages/tqdm/std.py", line 1291, in close
    if self.last_print_t < self.start_t + self.delay:
AttributeError: 'tqdm' object has no attribute 'last_print_t'
```
This is the code fragment...
```Python
with get(fileLink, stream=True, verify=True, timeout=60) as res:
        if res.status_code == 200:
            fileSize = res.headers.get('content-length', 0)
            with open(fileName, 'wb') as podcastFile, \
                tqdm(desc=fileName, total=fileSize, unit='iB', unit_scale=True, unit_divisor=1024) as bar:
                for chunk in res.iter_content(chunk_size=8192):
                    size = podcastFile.write(chunk)
                    print(size)
                    bar.update(size)
```

**Comment by frankiedrake** [comment]
> Got this error in 4.64.1 while trying to use tqdm(list(...), total=len(...)) but instead wrote tqdm(list(...), len(...)) as positional arg

I've got the same... Works nice when running plain python script, but with `gunicorn + Flask` - it fails.

**Comment by mzpqnxow** [comment]
I encounter this one out of every 5-6 runs when when combining dask and swifter, like so:

```python
            self.dd = dd.from_pandas(self.df, npartitions=12)
            ...
            target_df = (
                self.dd.loc[hostnames_mask]
                .map_partitions(
                    # Commented out line triggers tqdm race condition
                    # lambda df:df[["hostnames", "addr"]].swifter.apply(
                    lambda df: df[["hostnames", "addr"]].apply(
                        lambda row: nm_extract_names(row.hostnames, row.addr),
                        axis=1,
                        result_type="expand",
                    ),
                    meta={"scan_name": "str", "fqdn": "str", "addr": "str"},
                )
                .compute(scheduler="threads")
            )
```

First, I apologize for the ugly code

Second, I'm not sure that this is necessarily the fault of tqdm, but it seemed worth reporting

I'm not using tqdm directly, it's getting dragged in via dask and swifter. I would guess that it's possible that either swifter or dask are using tqdm improperly internally, making assumptions that they don't need to be thread-safe and perhaps not using a thread-safe tqdm object/method (if such a thing exists)

I'm not blocked, I'll just not use swifter for this as it's not terribly useful in this pattern (I actually forget I had left swifter in the apply call)

If it's helpful, the dataset is very large- a few million rows

**Comment by louismartin** [comment]
Getting this issue with `tqdm==4.66.4` in a multiprocess setting with this bit of code:
```
    tqdm(
                enumerate(iterator),
                total=len(samples),
                desc=f"{Path(output_file).name}",
            ):
```

**Comment by agonzalezd** [comment]
As I found, I had this error thrown due to a previous exception:

```
Traceback (most recent call last):
  File "/opt/LibriVox/create_librivox_corpus.py", line 104, in <module>
    tqdm(total=max_seconds, bar_format="{desc}: {percentage:.10f}%|{bar}| {n:.1f}/{total_fmt:.0f} [{elapsed}<{remaining}") as pbar):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 1098, in __init__
    self.refresh(lock_args=self.lock_args)
  File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 1347, in refresh
    self.display()
  File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 1495, in display
    self.sp(self.__str__() if msg is None else msg)
            ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 1151, in __str__
    return self.format_meter(**self.format_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 631, in format_meter
    nobar = bar_format.format(bar=full_bar, **format_dict)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'
Exception ignored in: <function tqdm.__del__ at 0x7f28d5bc0ae0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 1277, in close
    if self.last_print_t < self.start_t + self.delay:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'tqdm' object has no attribute 'last_print_t'
```

In my case, the error `'tqdm' object has no attribute 'last_print_t'` was solved once I solved the incorrect formating for `bar_format`. The true exception was `ValueError: Unknown format code 'f' for object of type 'str'`. 

Hope this helps anyone. However, a clearer message of the previous message could be improved, but I believe the code should not ignore the previous exception.
