### ISSUE TITLE
4.11.2: four test failures

### ISSUE THREAD

**Issue by 0-wiz-0** [tqdm/tqdm#344]
When running the tests on NetBSD-7.99.59/amd64 with python-3.6.0,
there are four test failures:
````
======================================================================
ERROR: tests_main.test_main
Test command line pipes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File ".../tqdm-4.11.2/tqdm/tests/tests_main.py", line 38, in test_main
    main()
  File ".../tqdm-4.11.2/tqdm/_main.py", line 165, in main
    with tqdm(**tqdm_args) as t:
  File ".../tqdm-4.11.2/tqdm/_tqdm.py", line 677, in __init__
    ncols = _environ_cols_wrapper()(file)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: tests_main.test_main
Test command line pipes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.6/site-packages/nose/case.py", line 276, in tearDown
    try_run(self.test, names)
  File "/usr/pkg/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File ".../tqdm-4.11.2/tqdm/tests/tests_tqdm.py", line 118, in posttest
    "{0} `tqdm` instances still in existence POST-test".format(n))
OSError: 1 `tqdm` instances still in existence POST-test

======================================================================
ERROR: tests_tqdm.test_write
Test write messages
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File ".../tqdm-4.11.2/tqdm/tests/tests_tqdm.py", line 1331, in test_write
    bar_format='{l_bar}', mininterval=0, miniters=1)
  File ".../tqdm-4.11.2/tqdm/_tqdm.py", line 677, in __init__
    ncols = _environ_cols_wrapper()(file)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: tests_tqdm.test_write
Test write messages
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.6/site-packages/nose/case.py", line 276, in tearDown
    try_run(self.test, names)
  File "/usr/pkg/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File ".../tqdm-4.11.2/tqdm/tests/tests_tqdm.py", line 118, in posttest
    "{0} `tqdm` instances still in existence POST-test".format(n))
OSError: 1 `tqdm` instances still in existence POST-test

----------------------------------------------------------------------
Ran 53 tests in 12.753s

FAILED (errors=4, skipped=6)
````

**Comment by casperdcl** [comment]
Thanks @0-wiz-0. Can you confirm this fixes your problem?

**Comment by 0-wiz-0** [comment]
I've applied https://github.com/tqdm/tqdm/commit/a379e330d013cf5f7cec8e9460d1d5e03b543444 on top of 4.11.2. This fixes the four tests for me:
````
Ran 53 tests in 15.956s

OK (skipped=6)
````

Thank you for the quick fix!
