### ISSUE TITLE
unicode unit problem on python 2.7

### ISSUE THREAD

**Issue by tiagocoutinho** [tqdm/tqdm#365]
I am using tqdm 4.11.2 with python 2.7.12 on a linux mint 18.1 64bits.
The the following example:
```python
from tqdm import trange

for i in trange(10, unit=u'\u00b0'):
    pass
```

gives me:

```python
Traceback (most recent call last):
  File "tqdm1.py", line 4, in <module>
    for i in trange(10, unit=u'\u00b0'):
  File "[...]local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 1118, in trange
    return tqdm(_range(*args), **kwargs)
  File "[...]local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 742, in __init__
    self.postfix))
  File "[...]local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 295, in format_meter
    ', '+postfix if postfix else '')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 1: ordinal not in range(128)
```

Since, by default, `ascii=False` in the tqdm constructor, I was assuming tqdm was unicode all across the library. Please correct me if I am wrong and if so, would you consider having 100% unicode compatibility for python < 3 (I would be wiling to help).

**Comment by casperdcl** [comment]
Ah dreaded unicode errors. Feel free to submit a PR to improve support. One of our biggest problems is having to support everything from python 2.6 to 3.x simultaneously.
