### ISSUE TITLE
Flag "disable=true" does not work and produces and error

### ISSUE THREAD

**Issue by geiges** [tqdm/tqdm#406]
the example would be:
tqdm.tqdm(xrange(1000), disable=True)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xx/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm.py", line 660, in __init__
    self.pos = self._get_free_pos(self)
  File "/home/xx/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm.py", line 396, in _get_free_pos
    return max(inst.pos for inst in cls._instances
  File "/home/xx/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm.py", line 397, in <genexpr>
    if inst is not instance) + 1
AttributeError: 'tqdm' object has no attribute 'pos'

**Comment by casperdcl** [comment]
Oh interesting. The issue looks like it's to do with immediate destruction of the `tqdm` object. Replacing:

```python
tqdm.tqdm(xrange(1000), disable=True)
```
with
```python
t = tqdm.tqdm(xrange(1000), disable=True)
```
or even just using the iterable
```python
for i in tqdm.tqdm(xrange(1000), disable=True):
    ...
```
fixes this issue. Doesn't seem much point in trying to fix your issue as an instantly deleted object which is never used (whether a `tqdm` object or not) isn't really very useful.

**Comment by casperdcl** [comment]
happy to reopen if this is still a problem
