### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'start_t'

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm#418]
I was working with extracting a corpus of voices to so WaveNet could train on them so I could have it imitate the voice of a favored cartoon character of mine, when:

```
james@ss:/datadrive3$ python2 7zx.py VCTK-Corpus.tar.gz 
INFO: Extracting from 1 file(s)
  0%|                                                                     | 0.00/2.42G [00:00<?, ?B/s]
Traceback (most recent call last):
  File "7zx.py", line 116, in <module>
    main()
  File "7zx.py", line 105, in main
    t.start_t - tall.start_t) + ' ' +
AttributeError: 'tqdm' object has no attribute 'start_t'
```

```
james@ss:/datadrive3$ pip2 install --upgrade tqdm
Requirement already up-to-date: tqdm in /usr/local/lib/python2.7/dist-packages
james@ss:/datadrive3$ pip3 install --upgrade tqdm
Requirement already up-to-date: tqdm in /usr/local/lib/python3.5/dist-packages
```

Additionally, when using Python 3, there's a missing `.decode('utf-8')`, and after that's fixed, I get this error:

```
Traceback (most recent call last):
  File "7zx.py", line 116, in <module>
    main()
  File "7zx.py", line 58, in main
    assert(sum(map(int, (inf[s] for inf in finfo[:-1]))) == totals[s])
TypeError: 'map' object is not subscriptable
```

Still additionally, using the `-O` flag to disable asserts gets me a nonmoving progress bar with the end as 2.42G when the size of the compressed archive is >10GB.

**Comment by leobuskin** [comment]
Same problem and it's related to https://github.com/tqdm/tqdm/issues/323, I'm pretty sure.
