### ISSUE TITLE
Undefined error when using in shell

### ISSUE THREAD

**Issue by regevs** [tqdm/tqdm#421]
Using tqdm in the context of a shell returns an undefined error and hangs:

```
$ find . -name '*.py' -exec cat \{} \; | tqdm | wc -l

Error:
Usage:
  tqdm [--help | options]
^\Quit
```

I suspect this is an installation problem, since it works for me on another computer, but I uninstalled and reinstalled from conda to no avail. I have no clue how to fix this.

**Comment by casperdcl** [comment]
Hmm. What's the output of `tqdm --version` and what shell are you using?

**Comment by regevs** [comment]
```
$ tqdm --version
4.15.0

$ python
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>>

$ bash --version
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by casperdcl** [comment]
Does it work if you do something like `seq 1000 | tqdm | wc -l`?

**Comment by regevs** [comment]
```
$ seq 1000 | tqdm | wc -l

Error:
Usage:
  tqdm [--help | options]
Traceback (most recent call last):
  File "/home/ec2-user/anaconda2/bin/tqdm", line 6, in <module>
    sys.exit(tqdm._main.main())
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_main.py", line 146, in main
    raise TqdmKeyError(str(e))
tqdm._tqdm.TqdmKeyError: "'user/anaconda2/bin/tqdm'"
1000
```

**Comment by casperdcl** [comment]
This is weird. If you pip install this rather than via anaconda, are your issues fixed?

**Comment by regevs** [comment]
Nope:
```
$ /home/ec2-user/anaconda2/bin/pip  install tqdm
Collecting tqdm
  Downloading tqdm-4.15.0-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 5.7MB/s
Installing collected packages: tqdm
Successfully installed tqdm-4.15.0
[ec2-user@ip-10-217-0-114 matching]$ seq 1000 | tqdm | wc -l

Error:
Usage:
  tqdm [--help | options]
Traceback (most recent call last):
  File "/home/ec2-user/anaconda2/bin/tqdm", line 11, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_main.py", line 146, in main
    raise TqdmKeyError(str(e))
tqdm._tqdm.TqdmKeyError: "'user/anaconda2/bin/tqdm'"
1000
```

**Comment by casperdcl** [comment]
```sh
$ virtualenv create foo
$ source foo/bin/activate
(foo) $ pip install tqdm
(foo) $ seq 1000 | tqdm | wc -l
(foo) $ seq 1000 | python -m tqdm | wc -l

**Comment by regevs** [comment]
Nope...

```
$ /home/ec2-user/anaconda2/bin/pip uninstall tqdm
Uninstalling tqdm-4.15.0:
  /home/ec2-user/anaconda2/bin/tqdm
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm-4.15.0.dist-info/DESCRIPTION.rst
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm-4.15.0.dist-info/INSTALLER
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm-4.15.0.dist-info/METADATA
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm-4.15.0.dist-info/RECORD
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm-4.15.0.dist-info/WHEEL
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm-4.15.0.dist-info/entry_points.txt
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm-4.15.0.dist-info/metadata.json
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm-4.15.0.dist-info/top_level.txt
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/__init__.py
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/__init__.pyc
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/__main__.py
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/__main__.pyc
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_main.py
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_main.pyc
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm.py
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm.pyc
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm_gui.py
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm_gui.pyc
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm_notebook.py
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm_notebook.pyc
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm_pandas.py
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm_pandas.pyc
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_utils.py
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_utils.pyc
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_version.py
  /home/ec2-user/anaconda2/lib/python2.7/site-packages/tqdm/_version.pyc
Proceed (y/n)? y
  Successfully uninstalled tqdm-4.15.0

$ virtualenv foo
New python executable in foo/bin/python2.7
Also creating executable in foo/bin/python
Installing setuptools, pip...done.

$ source foo/bin/activate

(foo) $ pip install tqdm
You are using pip version 6.0.8, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting tqdm
  Using cached tqdm-4.15.0-py2.py3-none-any.whl
Installing collected packages: tqdm

Successfully installed tqdm-4.15.0

(foo) $ seq 1000 | tqdm | wc -l

Error:
Usage:
  tqdm [--help | options]
Traceback (most recent call last):
  File "/home/ec2-user/foo/bin/tqdm", line 11, in <module>
    sys.exit(main())
  File "/home/ec2-user/foo/local/lib/python2.7/dist-packages/tqdm/_main.py", line 146, in main
    raise TqdmKeyError(str(e))
tqdm._tqdm.TqdmKeyError: "'user/foo/bin/tqdm'"
1000
```

**Comment by casperdcl** [comment]
As per #423 it looks like this is due to `ec2-user`.... the dash in your path is confusing my regex. Will fix shortly.

**Comment by regevs** [comment]
Thanks!
