### ISSUE TITLE
Command line argument parsing fails if script name contains dash

### ISSUE THREAD

**Issue by mvoelk** [tqdm/tqdm#423]
```
(venv) mmh-mv@pc:/$ tqdm
argv ['/home/mmh', 'mv/venv/bin/tqdm', '']
opts {'mv/venv/bin/tqdm': ''}

Error:
Usage:
  tqdm [--help | options]
^CTraceback (most recent call last):
  File "/home/mmh-mv/venv/lib/python3.5/site-packages/tqdm/_main.py", line 149, in main
    tqdm_args[o] = cast(v, opt_types[o])
KeyError: 'mv/venv/bin/tqdm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmh-mv/venv/lib/python3.5/site-packages/tqdm/_main.py", line 151, in main
    raise TqdmKeyError(str(e))
tqdm._tqdm.TqdmKeyError: "'mv/venv/bin/tqdm'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmh-mv/venv/bin/tqdm", line 11, in <module>
    sys.exit(main())
  File "/home/mmh-mv/venv/lib/python3.5/site-packages/tqdm/_main.py", line 155, in main
    for i in sys.stdin:
KeyboardInterrupt
```

I tried to fix `RE_SHLEX = re.compile(r'\s*--?([^\s=]+)(?:\s*|=|$)')` and quickly gave it up...

Is it an option to use the argparse module?

**Comment by mvoelk** [comment]
```
    argv = RE_SHLEX.split(' '.join(sys.argv[1:]))
    opts = dict(zip(argv[1::2], argv[2::2]))
```
works for me

**Comment by casperdcl** [comment]
Wait, you mean your script path is `/home/mmh-mv/venv/bin/tqdm`?

**Comment by casperdcl** [comment]
Ah nice, this is the same as #421

**Comment by casperdcl** [comment]
Will fix there, thx
