### ISSUE TITLE
pip install not working on os x

### ISSUE THREAD

**Issue by ahundt** [tqdm/tqdm#429]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

I'm on os x with homebrew python and tdqm does not seem to be in pypi for this setup:

```
± pip install tdqm
Collecting tdqm
  Could not find a version that satisfies the requirement tdqm (from versions: )
No matching distribution found for tdqm
```

same with pip3:

```
pip3 install tdqm
Collecting tdqm
  Could not find a version that satisfies the requirement tdqm (from versions: )
No matching distribution found for tdqm
```

python versions:

```
± python --version
Python 2.7.13

± python3 --version
Python 3.6.2
```

**Comment by casperdcl** [comment]
... unless pypi was down, perhaps there's an issue with your internet connection? Could you install other pypi modules?

**Comment by ahundt** [comment]
Yep, for example `pip install pybullet --upgrade` worked perfectly.

**Comment by ahundt** [comment]
I don't have any pypi expertise, but I know for example `tensorflow-gpu` (correctly) no longer installs the current version on os x because it is no longer supported, so I know a mechanism exists by which packages can be made available only on specific platforms, perhaps something like that needs to be corrected?

**Comment by casperdcl** [comment]
ah will check

**Comment by casperdcl** [comment]
`tqdm` is tagged to work specifically with MacOS X... what specific setup are you using?

**Comment by ahundt** [comment]
```
± pip install -vvv tdqm
Collecting tdqm
  1 location(s) to search for versions of tdqm:
  * https://pypi.python.org/simple/tdqm/
  Getting page https://pypi.python.org/simple/tdqm/
  Looking up "https://pypi.python.org/simple/tdqm/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/tdqm/ HTTP/1.1" 404 33
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/tdqm/: 404 Client Error: Not Found (tdqm does not exist) for url: https://pypi.python.org/simple/tdqm/ - skipping
  Could not find a version that satisfies the requirement tdqm (from versions: )
Cleaning up...
No matching distribution found for tdqm
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python2.7/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for tdqm

```

homebrew python details:
```
± brew info python
python: stable 2.7.13 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python/2.7.13 (3,658 files, 50.6MB) *
  Poured from bottle on 2017-01-09 at 22:20:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb
==> Dependencies
Build: sphinx-doc ✘, pkg-config ✔
Required: openssl ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔
Optional: sphinx-doc ✘, tcl-tk ✘, berkeley-db@4 ✘
==> Options
--with-berkeley-db@4
	Build with berkeley-db@4 support
--with-poll
	Enable select.poll, which is not fully implemented on macOS (https://bugs.python.org/issue5154)
--with-quicktest
	Run `make quicktest` after the build (for devs; may fail)
--with-sphinx-doc
	Build HTML documentation
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--without-gdbm
	Build without gdbm support
--without-readline
	Build without readline support
--without-sqlite
	Build without sqlite support
--HEAD
	Install HEAD version
==> Caveats
This formula installs a python2 executable to /usr/local/bin.
If you wish to have this formula's python executable in your PATH then add
the following to ~/.bash_profile:
  export PATH="/usr/local/opt/python/libexec/bin:$PATH"

Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python.html
```

homebrew python3 details:
```
± brew info python3
python3: stable 3.6.2 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python3/3.6.0 (3,049 files, 48.2MB)
  Poured from bottle on 2017-01-09 at 22:26:19
/usr/local/Cellar/python3/3.6.0_1 (3,671 files, 56.5MB)
  Poured from bottle on 2017-03-12 at 15:38:14
/usr/local/Cellar/python3/3.6.2 (3,777 files, 58.1MB) *
  Poured from bottle on 2017-08-09 at 14:41:10
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python3.rb
==> Dependencies
Build: pkg-config ✔, sphinx-doc ✘
Required: openssl ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔, xz ✔
Optional: tcl-tk ✘, sphinx-doc ✘
==> Options
--with-quicktest
	Run `make quicktest` after the build
--with-sphinx-doc
	Build HTML documentation
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--without-gdbm
	Build without gdbm support
--without-readline
	Build without readline support
--without-sqlite
	Build without sqlite support
--without-xz
	Build without xz support
--HEAD
	Install HEAD version
==> Caveats
Pip, setuptools, and wheel have been installed. To update them
  pip3 install --upgrade pip setuptools wheel

You can install Python packages with
  pip3 install <package>

They will install into the site-package directory
  /usr/local/lib/python3.6/site-packages

See: https://docs.brew.sh/Homebrew-and-Python.html
```

**Comment by ahundt** [comment]
Hmm it seems someone had a certificate issue once:
https://github.com/Homebrew/legacy-homebrew/issues/41253

but I don't have the files they mentioned there. Has anyone else seeing this installed on OS X recently?

I wonder if it is a problem local to just me.

**Comment by casperdcl** [comment]
This is odd... if you point your browser to

https://pypi.python.org/simple/tqdm/

it correctly lists links.

https://pypi.python.org/simple/tdqm/

however (copy-pasted from your output) doesn't work for me

**Comment by casperdcl** [comment]
oh wait. hah. it's tqdm, not tdqm.

**Comment by ahundt** [comment]
LOL, I'm sorry about that! The correct name worked, go figure...

**Comment by gabrer** [comment]
I have come across the same issue and the same cause (i.e. tdqm).. thank you guys! :)

**Comment by casperdcl** [comment]
I think you mean *te quiero demasiado*. We're making *taqadum*!

**Comment by Linao1996** [comment]
yeah，the correct name is tqdm...thanks you guys!
