### ISSUE TITLE
frac division tries to divide two strings

### ISSUE THREAD

**Issue by dprhate** [tqdm/tqdm#453]
Installing sysutils/py3-iocage from ports yields the following python stack trace error on invocation of `iocage fetch`:

[root@vultr ]# iocage fetch
********************************************************************************
fdescfs(5) is not mounted, performance  may suffer. Please run:
mount -t fdescfs fdesc /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdesc /dev/fd  fdescfs  rw  0  0
********************************************************************************

[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE
[5] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1)
Type EXIT to quit: 5
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 474, in fetch_ftp_release
    self.fetch_download(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 701, in fetch_download
    unit_scale="mega")
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 867, in __init__
    self.postfix, unit_divisor))
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 339, in format_meter
    frac = n / total
TypeError: unsupported operand type(s) for /: 'str' and 'str

Tested on desktop, OVH VPS, and fresh install on a Vultr VPS. All FreeBSD version 11.1-RELEASE-p1-amd64.

Steps to replicate:
iocage activate zroot
iocage fetch

I've tried a number of wrappings for the equation eg, frac= int(n) / total and float(total) and so forth... to no real change. If this is an iocage issue please let me know.

**Comment by casperdcl** [comment]
Do you have code somewhere? [iocage/iocage@0.9.9.2:iocage/lib/ioc_fetch.py#L784](https://github.com/iocage/iocage/blob/0.9.9.2/iocage/lib/ioc_fetch.py#L784) seems fine.

**Comment by dprhate** [comment]
Fresh install on the Vultr VPS:
portsnap fetch extract,
(install portmaster)
portinstall -v --batch py3-iocage (py2-iocage yields no change.)
iocage activate zroot
iocage fetch

**Comment by casperdcl** [comment]
Oh I commented on this issue before:

[iocage/iocage#302](https://github.com/iocage/iocage/issues/302), [iocage/iocage#359](https://github.com/iocage/iocage/issues/359)

This was fixed in https://github.com/iocage/iocage/commit/d55c9387c5dbc220bded2125d5167ef426eb09ea so you need to ensure you have `iocage>=0.9.9.2`

Don't know about `portinstall`, perhaps @skarekrow can help

**Comment by skarekrow** [comment]
@dprhate The latest iocage that uses this was tagged yesterday. It’s going to be a bit before it’s in ports. @araujobsd would know when exactly :like:

**Comment by dprhate** [comment]
It appears I didn't do a thorough search in the issues section. Thank you for pointing that out though. I filed a PR on freebsd's bug tracker and @araujobsd is the assignee, when I didn't get a reply (after a couple days) I tried here.

Reference: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222666

Thanks for the help, I'll try it manually and hope nothing else breaks. Cheers!

**Comment by skarekrow** [comment]
@dprhate Thank you! I’ll ping him offline and see what’s up as well :)
