### ISSUE TITLE
Test fails on 32-bit Intel

### ISSUE THREAD

**Issue by andreasbaumann** [tqdm/tqdm#538]
I get on Archlinux32, 32-bit Intel:

```
======================================================================
FAIL: Test on multiple bars, one not needing miniters adjustment
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/python-tqdm/src/tqdm-4.22.0-py2/tqdm/tests/tests_synchronisation.py", line 160, in test_monitoring_multi
    assert t2.miniters == 500  # check that t2 was not adjusted
AssertionError

----------------------------------------------------------------------
Ran 55 tests in 7.111s

FAILED (SKIP=6, failures=1)
```

Archlinux builds Python2 and Python3 in one package description, the failing one is with

```
python2 setup.py nosetests --ignore-files="tests_perf\.py"
```

**Comment by casperdcl** [comment]
Just updated quite a lot of the tests in #1046 and #1044... is this still an issue?

**Comment by andreasbaumann** [comment]
Just done a build on 32-bit, seems all ok.

**Comment by casperdcl** [comment]
ok closing for now then
