### ISSUE TITLE
Conflict between tqdm and multiprocessing on windows using anaconda

### ISSUE THREAD

**Issue by schwemro** [tqdm/tqdm#542]
Apparently, there occurs a conflict between tqdm and multiprocessing. There is an `AttributeError` displayed. I provide here an minimal working example. It works on UNIX but unfortunately not on windows. Here is my code:

     # -*- coding: utf-8 -*-
     from tqdm import tqdm
     from time import sleep
     from tqdm import trange
     from multiprocessing import Pool, freeze_support, RLock

     L = list(range(9))

    def progresser(n):
       interval = 0.001 / (n + 2)
       total = 5000
       text = "#{}, est. {:<04.2}s".format(n, interval * total)
       for i in trange(total, desc=text, position=n):
          sleep(interval)

    if __name__ == '__main__':
        freeze_support()  # for Windows support
        p = Pool(len(L),
                 # again, for Windows support
                 initializer=tqdm.set_lock, initargs=(RLock(),))
        p.map(progresser, L)
        print("\n" * (len(L) - 2))

An here is the traceback:

    Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 
    16:13:55) [MSC v.1900 64 bit (AMD64)]
    Type "copyright", "credits" or "license" for more information.

    IPython 6.3.1 -- An enhanced Interactive Python.

    runfile('C:/Users/Downloads/temp.py', 
    wdir='C:/Users/Downloads')
    Traceback (most recent call last):

    File "<ipython-input-1-8046ea5eaef4>", line 1, in <module>
    runfile('C:/Users/Downloads/temp.py', 
    wdir='C:/Users/Downloads')

    File "C:\ProgramData\Anaconda3\lib\site- 
    packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

    File "C:\ProgramData\Anaconda3\lib\site- 
    packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

    File "C:/Users/Downloads/temp.py", line 22, in <module>
    p.map(progresser, L)

    File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 
    266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

    File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 
    644, in get
    raise self._value

    AttributeError: 'NoneType' object has no attribute 'write'

I need to run it on the windows machine since it requires some CPU power which is not given by my notebook. I'm confused because in the conda environments I've installed the exact same libraries.

**Comment by casperdcl** [comment]
I can't reproduce this on linux py36 - could you try with `tqdm>=4.23.1`?

**Comment by schwemro** [comment]
@alexdaniilidis Unfortunately it is not similiar.

@casperdcl I have also been trying it on Windows 10 with version 4.23.3 but without being successful.

**Comment by casperdcl** [comment]
I'll need to test this sometime on a windows machine...

**Comment by jixian79** [comment]
same issue。
i use anaconda python3.6.5  pytorch0.4 。
```
import torch
from tqdm import tqdm
from torch.utils.data import DataLoader

from torch.utils.data import Dataset

class TSPDataset(Dataset):
    
    def __init__(self, filename=None, size=50, num_samples=1000000):
        super(TSPDataset, self).__init__()

        self.data_set = []
        if filename is not None:
            assert os.path.splitext(filename)[1] == '.pkl'

            with open(filename, 'rb') as f:
                data = pickle.load(f)
                self.data = [torch.FloatTensor(row) for row in data[:num_samples]]
        else:
            # Sample points randomly in [0, 1] square
            self.data = [torch.FloatTensor(size, 2).uniform_(0, 1) for i in range(num_samples)]

        self.size = len(self.data)

    def __len__(self):
        return self.size

    def __getitem__(self, idx):
        return self.data[idx]

    
class TSP(object):

    NAME = 'tsp'

    @staticmethod
    def get_costs(dataset, pi):
        """
        :param dataset: (batch_size, graph_size, 2) coordinates
        :param pi: (batch_size, graph_size) permutations representing tours
        :return: (batch_size) lengths of tours
        """

        # Check that tours are valid, i.e. contain 0 to n -1
        assert (
            torch.arange(pi.size(1), out=pi.data.new()).view(1, -1).expand_as(pi) ==
            pi.data.sort(1)[0]
        ).all(), "Invalid tour"

        # Gather dataset in order of tour
        d = dataset.gather(1, pi.unsqueeze(-1).expand_as(dataset))

        # Length is distance (L2-norm of difference) from each next location from its prev and of last from first
        return (d[:, 1:] - d[:, :-1]).norm(p=2, dim=2).sum(1) + (d[:, 0] - d[:, -1]).norm(p=2, dim=1), None  # 

    @staticmethod
    def make_dataset(*args, **kwargs):
        return TSPDataset(*args, **kwargs)

def load_problem(name):
    problem = {
        'tsp': TSP,
    }.get(name, None)
    assert problem is not None, "Currently unsupported problem: {}!".format(name)
    return problem

problem = load_problem('tsp')

training_dataset = problem.make_dataset(size=20, num_samples=512000)
training_dataloader = DataLoader(training_dataset, batch_size=512, num_workers=2)

i = 0
for batch_id, batch in enumerate(tqdm(training_dataloader, disable=False)):
    i += 1
``` 

**it stucks at the bars**
**no process made by qdm**
But! when you change the num_workers =0 , means to use the main process to load the data, it runs well .

**Comment by CentralLT** [comment]
Any progress on this issue?
