### ISSUE TITLE
Random deadlocks with multiprocessing

### ISSUE THREAD

**Issue by Microsheep** [tqdm/tqdm#627]
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

System Info
```
tqdm.__version__: 4.26.0
sys.version: 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
sys.platform: linux
```

Code that can have the problem
```python
import math
import multiprocessing
from functools import wraps

from tqdm import tqdm

def MP_TQDM(func, shared=[], args=[], sz=1, pc=2, reset=True):
    def chunks(l, n):
        for i in range(0, len(l), n):
            yield (pc, shared, l[i:i + n])
    rets = []
    with multiprocessing.Pool(pc, maxtasksperchild = 1 if reset else None) as p:
        # The master process tqdm bar is at Position 0
        for ret in tqdm(p.imap_unordered(func, chunks(args, sz)), total=math.ceil(len(args)/sz)):
            rets += ret
    return rets

def MP_TQDM_WORKER(func):
    @wraps(func)
    def d_func(*args, **kwargs):
        pc, shared, argset = args[0]
        # The worker process tqdm bar shall start at Position 1
        worker_id = (multiprocessing.current_process()._identity[0]-1)%pc + 1
        rets = []
        for arg in tqdm(argset, position=worker_id):
            rets.append(func(shared, arg))
        return rets
    return d_func

@MP_TQDM_WORKER
def myfunc(shared, args):
    return shared[0]*args

if __name__ == "__main__":
    N = 99999000
    M = 10
    ANS = MP_TQDM(myfunc, shared=[M], args=range(1, N+1), sz=1000000, pc=8, reset=True)
    assert sum(ANS) == (N*(N+1)/2)*M
```

Random deadlocks can happen to this piece of dummy code that I wrote.
The probability increases when process count (pc) is larger or total job (N) is larger.

I am trying to write a piece of utility code that I can use to wrap around other functions to make it run in multiprocessing while showing two sections of progress bar.
The first progress bar will show the total chunks of work needed.
The second section of progress bar will show the progress for each process.

Some of the tracebacks after sending KeyboardInterrupt
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "tq.py", line 24, in d_func
    for arg in tqdm(argset, position=worker_id):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 958, in __iter__
    with self._lock:
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 106, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 99, in acquire
    lock.acquire()
```
```
Traceback (most recent call last):
  File "tq.py", line 36, in <module>
    ANS = MP_TQDM(myfunc, shared=[M], args=range(1, N+1), sz=1000000, pc=8, reset=True)
  File "tq.py", line 13, in MP_TQDM
    for ret in tqdm(p.imap_unordered(func, chunks(args, sz)), total=math.ceil(len(args)/sz)):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 958, in __iter__
    with self._lock:
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 106, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 99, in acquire
    lock.acquire()
```
```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 889, in __del__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 1087, in close
    if self.disable:
AttributeError: 'tqdm' object has no attribute 'disable'
```

**Comment by Ninpo** [comment]
I've seen a similar issue with this but it's harder to recreate.  I'm passing a progress bar to different asyncio workers and the app will occasionally hang with lock.acquire() in the traceback after a few CTRL+Cs.  I'll update with a traceback if it happens again/I can find the last one.

**Comment by casperdcl** [comment]
Is this only an issue with KeyboardInterrupts?

**Comment by casperdcl** [comment]
I'm just wondering if the deadlock is caused by KeyboardInterrupts (#548)

**Comment by Ninpo** [comment]
I don't understand how a KeyboardInterrupt could cause the deadlock when the KeyboardInterrupt doesn't happen until _after_ the app in question has hung and a CTRL+C (KeyboardInterrupt) is required to make it end...

**Comment by Ninpo** [comment]
If you're asking if my app also makes sure KeyboardInterrupts are caught, yes it does, due to the fact the Trio async library I use ensures CTRL+C works properly.

**Comment by koriakin** [comment]
I have traced it down to a pypy bug, which has just been fixed on pypy master: https://bitbucket.org/pypy/pypy/issues/2953/deadlock, would be nice to get a confirmation with nightly pypy.

**Comment by casperdcl** [comment]
closing as duplicate of #528, happy to reopen if different

**Comment by Microsheep** [comment]
@casperdcl I think this might be different, I am not using pypy, but using CPython.

I have tested the same code again with a newer version of tqdm.
The problem still exists.

System Info
```
>>> import tqdm, sys, platform
>>> print(tqdm.__version__, sys.version, sys.platform, platform.python_implementation())
4.31.1 3.7.0 (default, Jun 28 2018, 13:15:42) [GCC 7.2.0] linux CPython
```
```
tqdm.__version__: 4.31.1
sys.version: 3.7.0 (default, Jun 28 2018, 13:15:42) [GCC 7.2.0]
sys.platform: linux
platform.python_implementation(): CPython
```
(BTW, I think adding the platform.python_implementation to Issue Template might be helpful)

I had used pipenv to ensure that the environment shall be clean.
```
>>> pipenv run pip list
Package       Version
------------- -------
pip           19.1.1
pkg-resources 0.0.0
setuptools    41.0.1
tqdm          4.31.1
wheel         0.33.2
```

Updated Tracebacks:
It seems that sometimes the lock is not in `__iter__` but in `__new__`
```
Traceback (most recent call last):
  File "/home/micro/LIB/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/micro/LIB/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/micro/LIB/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "test.py", line 25, in d_func
    for arg in tqdm(argset, position=worker_id):
  File "/home/micro/.local/share/virtualenvs/tqdmtest-XjjyYyr-/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1041, in __iter__
    with self._lock:
  File "/home/micro/.local/share/virtualenvs/tqdmtest-XjjyYyr-/lib/python3.7/site-packages/tqdm/_tqdm.py", line 98, in __enter__
    self.acquire()
  File "/home/micro/.local/share/virtualenvs/tqdmtest-XjjyYyr-/lib/python3.7/site-packages/tqdm/_tqdm.py", line 91, in acquire
    lock.acquire()
```
```
Traceback (most recent call last):
  File "/home/micro/LIB/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/micro/LIB/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/micro/LIB/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "test.py", line 25, in d_func
    for arg in tqdm(argset, position=worker_id):
  File "/home/micro/.local/share/virtualenvs/tqdmtest-XjjyYyr-/lib/python3.7/site-packages/tqdm/_tqdm.py", line 466, in __new__
    with cls.get_lock():
  File "/home/micro/.local/share/virtualenvs/tqdmtest-XjjyYyr-/lib/python3.7/site-packages/tqdm/_tqdm.py", line 98, in __enter__
    self.acquire()
  File "/home/micro/.local/share/virtualenvs/tqdmtest-XjjyYyr-/lib/python3.7/site-packages/tqdm/_tqdm.py", line 91, in acquire
    lock.acquire()
```
```
Exception ignored in: <function tqdm.__del__ at 0x7f82116b9048>
Traceback (most recent call last):
  File "/home/micro/.local/share/virtualenvs/tqdmtest-XjjyYyr-/lib/python3.7/site-packages/tqdm/_tqdm.py", line 966, in __del__
    self.close()
  File "/home/micro/.local/share/virtualenvs/tqdmtest-XjjyYyr-/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1158, in close
    if self.disable:
AttributeError: 'tqdm' object has no attribute 'disable'
```

I think the deadlock happens when multiple child progress bars completed.
(This might not be correct since it is just a feeling)

**Comment by fake-name** [comment]
I'm seeing something that looks like this too.

I think it can also occur with gevent based greenthreads.

**Comment by fake-name** [comment]
```
<Thread(Thread-13, started daemon 139628740847360)>
  File "/opt/pypy3/lib-python/3/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/opt/pypy3/lib-python/3/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/pypy3/lib-python/3/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/pypy3/lib-python/3/concurrent/futures/thread.py", line 66, in _worker
    work_item.run()
  File "/opt/pypy3/lib-python/3/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/pypy3/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/media/Scripts/ReadableWebProxy/ndscheduler/ndscheduler/core/scheduler/base.py", line 45, in run_job
    cls.run_scheduler_job(job_class, job_id, execution_id, *args, **kwargs)
  File "/media/Scripts/ReadableWebProxy/ndscheduler/ndscheduler/core/scheduler/base.py", line 67, in run_scheduler_job
    job_class.run_job(job_id, execution_id, *args, **kwargs)
  File "/media/Scripts/ReadableWebProxy/ndscheduler/ndscheduler/job.py", line 113, in run_job
    result = job.run(*args, **kwargs)
  File "/media/Scripts/ReadableWebProxy/scheduled_jobs/python_job.py", line 34, in run
    instance.go()
  File "/media/Scripts/ReadableWebProxy/Misc/NuForwarder/NuHeader.py", line 767, in go
    self.run()
  File "/media/Scripts/ReadableWebProxy/Misc/NuForwarder/NuHeader.py", line 781, in run
    self.transmit_since(ago)
  File "/media/Scripts/ReadableWebProxy/Misc/NuForwarder/NuHeader.py", line 568, in transmit_since
    self.retriggerUrlList(release_urls)
  File "/media/Scripts/ReadableWebProxy/WebMirror/TimedTriggers/TriggerBase.py", line 81, in retriggerUrlList
    WebMirror.UrlUpserter.do_link_batch_update_sess(self.log, sess, dictlinks, priority, show_progress=show_progress)
  File "/media/Scripts/ReadableWebProxy/WebMirror/UrlUpserter.py", line 288, in do_link_batch_update_sess
    for subc in misc.batch(link_batch, 50, show_progress=show_progress):
  File "/media/Scripts/ReadableWebProxy/common/util/misc.py", line 7, in batch
    for ndx in tqdm.tqdm(range(0, l, n)):
  File "/opt/pypy3/site-packages/tqdm/_tqdm.py", line 466, in __new__
    with cls.get_lock():
  File "/opt/pypy3/site-packages/tqdm/_tqdm.py", line 98, in __enter__
    self.acquire()
  File "/opt/pypy3/site-packages/tqdm/_tqdm.py", line 91, in acquire
    lock.acquire()

```

Still happens on `4.32.2`.

Why are any calls to `acquire()` made without a timeout? It seems to me that the options are try to lock (and maybe have corrupted console output if it fails), or force a lock (and maybe deadlock).

Personally, I'd really, **really** prefer occasional bogus console output over a progress bar library completely wedging my entire application.

**Comment by biswaz** [comment]
Happening in Cpython 2.7.15+
Debugged using gdb as shell is not responding to interrupts

`Traceback (most recent call first):
  Waiting for the GIL
  <built-in method acquire of thread.lock object at remote 0x7fb47e1869f0>
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
  File "/usr/lib/python2.7/threading.py", line 940, in join
    self.__block.wait()
  File "/root/.Envs/gdb/local/lib/python2.7/site-packages/tqdm/_monitor.py", line 53, in exit
    self.join()
  File "/root/.Envs/gdb/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 511, in _decr_instances
    cls.monitor.exit()
  File "/root/.Envs/gdb/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 1159, in close
    self._decr_instances(self)
  File "/root/.Envs/gdb/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 1071, in __iter__
    self.close()
  File "/root/deployments/healthbase/integrations/compile_healthbase_payer/models.py", line 284, in get_addresses
    for payer in tqdm(queryset_iterator(payer_objs, 10000), desc='getting addresses from Payer', total=payer_objs.count()):
  File "<ipython-input-3-0a8899218001>", line 6, in <module>
`

**Comment by fake-name** [comment]
**ALL** locks should be acquired with a timeout, without exception.

**Comment by casperdcl** [comment]
@fake-name probably even better is `lock_args=(False,)` (non-blocking locks)

**Comment by fake-name** [comment]
Yeah, but that'd require a lot more rework. Generally, you can transplant in timeouts to existing code without a lot of changes, and you'll only hit the timeout in a few oddball corner cases. 

In this case, you *want* to block until you synchronize, so if you use non-blocking, it just means you'll wind up implementing the timeout in your own code.

**Comment by casperdcl** [comment]
Erm you could just use a lock that has a default timeout on it's `acquire` method

**Comment by casperdcl** [comment]
Also not sure about ypur specific case but in general you don't necessarily need `tqdm` to block (i.e. it's better to refresh the bar less often - essentially dropping v. granular progress output because of lock contest)

**Comment by fake-name** [comment]
Huh? I was talking about the tqdm locks, though that's a valid point about just dropping updates.

This entire issue basically boils down to the weirdness that can happen when using a global lock.

**Comment by casperdcl** [comment]
> I was talking about the tqdm locks

Yes, which can be thought of as "locks on tqdm's screen output."

> This entire issue basically boils down to the weirdness that can happen when using a global lock.

Yes, though since there's only one physical screen output, I don't see any way around having one global lock for it. Concurrent applications always need to be careful about locks and the same applies when trying to use `tqdm` concurrently.

**Comment by fake-name** [comment]
Oh, derp. 

Anyways, I wonder if this issue could be caused by `fork()`ing while the lock is held. I've seen that cause problems before.

**Comment by biswaz** [comment]
Happening in Cpython 2.7.15+
Debugged using gdb as shell is not responding to interrupts
```
>>> import tqdm, sys, platform
>>> print(tqdm.__version__, sys.version, sys.platform, platform.python_implementation())
('4.32.2', '2.7.17 (default, Nov  7 2019, 10:07:09) \n[GCC 7.4.0]', 'linux2', 'CPython')
>>> 
```

```
Traceback (most recent call first):
  Waiting for the GIL
  <built-in method acquire of thread.lock object at remote 0x7fb47e1869f0>
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
  File "/usr/lib/python2.7/threading.py", line 940, in join
    self.__block.wait()
  File "/root/.Envs/gdb/local/lib/python2.7/site-packages/tqdm/_monitor.py", line 53, in exit
    self.join()
  File "/root/.Envs/gdb/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 511, in _decr_instances
    cls.monitor.exit()
  File "/root/.Envs/gdb/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 1159, in close
    self._decr_instances(self)
  File "/root/.Envs/gdb/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 1071, in __iter__
    self.close()
  File "../project/integrations/app/models.py", line 284, in get_addresses
    for payer in tqdm(queryset_iterator(payer_objs, 10000), desc='getting data', total=objs.count()):
  File "<ipython-input-3-0a8899218001>", line 6, in <module>
```

**Comment by kszlim** [comment]
Anyone know the status of this bug? I think I may be running into it as well.

**Comment by casperdcl** [comment]
The only way to deal with multiprocesses really is to share one lock object with all workers and use `tqdm.set_lock(lock)` in each worker.

The same applies to multithreading on py2.

Meanwhile multithreading on py3 should work without having to manually `set_lock`.

**Comment by biswaz** [comment]
@casperdcl tqdm uses multithreading to print the progress bar right? I had to pass a lock with a timeout to fix GIL deadlock from tqdm and my process was in single process/thread.  correct me if I'm wrong.

**Comment by casperdcl** [comment]
@biswaz that doesn't sound right. Printing isn't done in a separate thread or process.

Processes and threads are also very different.
Deadlocks by definition can't occur if you're not using either.

Depending on your framework you might actually be using threads even if you don't think so - e.g. django uses threads.

**Comment by mcemilg** [comment]
I have also encountered stuck in a similar use case. I was using the `progress_apply` interface for `pandas`. There is no other special use of threads. Somehow it stuck after the end of progress.

```
100%|██████████| 78620/78620 [01:00<00:00, 1753.47it/s]^CTraceback (most recent call last):                                                                                                         

(...)
                                                                                         
    unique_groups_df = unique_groups.progress_apply(link_group)                                                                                                                                                    
  File "/usr/local/lib/python3.8/site-packages/tqdm/std.py", line 770, in inner
    t.close()
  File "/usr/local/lib/python3.8/site-packages/tqdm/std.py", line 1271, in close
    self._decr_instances(self)
  File "/usr/local/lib/python3.8/site-packages/tqdm/std.py", line 572, in _decr_instances
    cls.monitor.exit()
  File "/usr/local/lib/python3.8/site-packages/tqdm/_monitor.py", line 53, in exit
    self.join()
  File "/usr/local/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
