### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by phil-marble** [tqdm/tqdm#628]
```
Collecting tqdm<5.0,>=4.11.2 (from moviepy<0.3.0,>=0.2.0)
  Downloading https://files.pythonhosted.org/packages/16/33/6d8bd6a7c4238f383426b7593bf05bfd6d9e1f10c3084b56c0f14d973754/tqdm-4.27.0-py2.py3-none-any.whl (44kB)
```

```
Installing collected packages: tqdm
  Found existing installation: tqdm 4.26.0
    Uninstalling tqdm-4.26.0:
      Successfully uninstalled tqdm-4.26.0
  Rolling back uninstall of tqdm
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 376, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 315, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: '/usr/local/man/man1'
```

I think you mean to install to: `/usr/local/share/man/man1/`

**Comment by phil-marble** [comment]
This is on Ubuntu Linux 16.04.05.

**Comment by casperdcl** [comment]
I don't have this issue on 16(LTS). I guess you're not using a virtualenv or conda etc? Just system's built-in python? How are you installing `tqdm`? Using `sudo pip` or `pip install --user`?
