### ISSUE TITLE
test issue in `Test multiprocessing.Pool` - `AttributeError: 'list' object has no attribute 'close'`

### ISSUE THREAD

**Issue by sandrotosi** [tqdm/tqdm#654]
Hello,
when preparing tqdm 4.28.1 for Debian, the test `multiprocessing.pool` is stuck in an "infinite loop" of:

```
Test multiprocessing.Pool ... Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    sys.stdin.close()
AttributeError: 'list' object has no attribute 'close'
Process PoolWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    sys.stdin.close()
AttributeError: 'list' object has no attribute 'close'
Process PoolWorker-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    sys.stdin.close()
AttributeError: 'list' object has no attribute 'close'
Process PoolWorker-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    sys.stdin.close()
AttributeError: 'list' object has no attribute 'close'
Process PoolWorker-5:
```

this is with python 2.7.15

can you have a look?

**Comment by casperdcl** [comment]
this is to do with a previous test which failed after patching `sys.stdin = list(...)` but before it could un-patch `sys.stdin = sys_stdin_original`. If you only run the multiprocessing tests by themselves (`nosetests tqdm/tests/tests_synchronisation.py -dv`), or fix the failing tests, this shouldn't be a problem.

**Comment by casperdcl** [comment]
will re-open if still an issue
