### ISSUE TITLE
Reopening a completed/finished/closed bar

### ISSUE THREAD

**Issue by akaniklaus** [tqdm/tqdm#661]
When I re-create tq object to reset the progress bar, it creates a new one. I would like to re-use the existing one in the console. Can you please let me know how I can reset the existing progress bar?

**Comment by akaniklaus** [comment]
I tried resetting via the following code rather than re-creating the object. However, now it just keep printing a new progress bar on a new line on each update.

```
            self.train_pb.n = 0
            self.train_pb.start_t = self.train_pb._time()
```

**Comment by casperdcl** [comment]
What do you mean by "resetting?"

1. setting a bar that's reached 100% back to 0?
2. setting a bar that's reached less than 100% back to 0?
3. doing one of the above when there are multiple parallel bars?

**Comment by akaniklaus** [comment]
@casperdcl The first one (setting a bar that's reached 100% back to 0) when there are multiple parallel bars. I also use enumerate over the defined bar in a loop. When I define a new loop right after resetting the bar back to 0%, the loop also should start from the first item.

**Comment by casperdcl** [comment]
related: #545

**Comment by akaniklaus** [comment]
@casperdcl I already tried setting ".n" and it should be automatically refreshed right afterwards when I am calling "set_description". All I am missing is the "sleep" but I guess when it is concurrent, other problems emerge. I also tried using "close" and re-initializing it but that even didn't work properly.

**Comment by akaniklaus** [comment]
@casperdcl Ok, I will try that as soon as possible. Thank you very much for your help. I didn't know creating several bars in parallel would classify as nested bars so haven't read that part of the documentation.

**Comment by akaniklaus** [comment]
@casperdcl It works generally quite well, I am just sometimes receiving the following error. May I please ask if you have any idea about that?

Exception in thread Thread-37:██████████████████▎                                                                                                               | 20/99 [00:19<01:25,  1.09s/it, Loss=0.938]
Traceback (most recent call last):███████████████████████▏                                                                                                     | 27/99 [00:25<01:15,  1.05s/it, Loss=0.960]
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                                                  | 29/99 [00:28<01:14,  1.06s/it, Loss=0.959]
    self.run() 24%|█████████████████████████████████▉                                                                                                          | 24/99 [00:22<01:17,  1.03s/it, Loss=0.921]
  File "<ipython-input-1-244ac92aeaa4>", line 63, in run                                                                                                       | 22/99 [00:21<01:18,  1.02s/it, Loss=0.926]
    self._train_iter()███████████████▍                                                                                                                         | 13/99 [00:13<01:33,  1.08s/it, Loss=0.941]
  File "<ipython-input-1-244ac92aeaa4>", line 116, in _train_iter                                                                                              | 12/99 [00:12<01:29,  1.03s/it, Loss=0.926]
    for i, (batch_features, batch_targets) in enumerate(self.train_pb):                                                                                         | 9/99 [00:09<01:33,  1.04s/it, Loss=0.927]
  File "/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1038, in __iter__                                                                          | 13/99 [00:13<01:32,  1.07s/it, Loss=0.926]
    self.close() 7%|█████████▉                                                                                                                                  | 7/99 [00:06<01:29,  1.03it/s, Loss=0.923]
  File "/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1133, in close                                                                              | 9/99 [00:09<01:35,  1.06s/it, Loss=0.932]
    self._decr_instances(self)█████████████▊                                                                                                                   | 17/99 [00:16<01:21,  1.00it/s, Loss=0.941]
  File "/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 490, in _decr_instances                                                                     | 2/99 [00:02<01:44,  1.07s/it, Loss=0.925]
    if inst.pos > abs(instance.pos):                                                                                                                            | 2/99 [00:02<01:48,  1.12s/it, Loss=0.921]
**AttributeError: 'tqdm' object has no attribute 'pos'**

**Comment by casperdcl** [comment]
you need to upgrade `tqdm` - `pip install -U tqdm` or simillar

**Comment by akaniklaus** [comment]
@casperdcl One last thing, the progress bar does not work properly when I use zip from itertools.

progress_bar = tq(zip(train_loader, train_shuffled))

**Comment by akaniklaus** [comment]
Ok, I just noticed that this is among "known issues". Thank you very much for your help!!!

**Comment by casperdcl** [comment]
:) see https://github.com/tqdm/tqdm#faq-and-known-issues, #256,

**Comment by casperdcl** [comment]
I'm still going to leave this issue (reopening a closed bar) open (even though all of your issues are fixed)

**Comment by akaniklaus** [comment]
@casperdcl It would be great if there was a way to prevent it from being messed up by other prints. I will have them in a log file but I am curious if there could be a better way such as dividing the console screen vertically for monitoring progress bars and other prints simultaneously.

**Comment by casperdcl** [comment]
https://github.com/tqdm/tqdm#redirecting-writing
