### ISSUE TITLE
v4.31.0 fails in Jenkins job: TypeError: encode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by beaverlyhills** [tqdm/tqdm#673]
Latest version of tqdm  v4.31.0 fails when executed as part of Jenkins job:
```python
Traceback (most recent call last):
  File "./patcher/env/bin/autopatch", line 11, in <module>
    load_entry_point('PearPatcher==0.1', 'console_scripts', 'autopatch')()
  File "build/bdist.macosx-10.13-x86_64/egg/pearpatcher/commandlineinterface.py", line 40, in main
  File "build/bdist.macosx-10.13-x86_64/egg/pearpatcher/util.py", line 58, in tracedFunctionWrapper
  File "build/bdist.macosx-10.13-x86_64/egg/pearpatcher/commandlineinterface.py", line 64, in run
  File "build/bdist.macosx-10.13-x86_64/egg/pearpatcher/util.py", line 58, in tracedFunctionWrapper
  File "build/bdist.macosx-10.13-x86_64/egg/pearpatcher/commandlineinterface.py", line 162, in patch_action
  File "build/bdist.macosx-10.13-x86_64/egg/pearpatcher/swiftscanner.py", line 52, in create_patches
  File "build/bdist.macosx-10.13-x86_64/egg/pearpatcher/util.py", line 58, in tracedFunctionWrapper
  File "build/bdist.macosx-10.13-x86_64/egg/pearpatcher/swiftscanner.py", line 61, in scan
  File "./patcher/env/lib/python2.7/site-packages/tqdm-4.31.0-py2.7.egg/tqdm/_tqdm.py", line 945, in __init__
    self.display()
  File "./patcher/env/lib/python2.7/site-packages/tqdm-4.31.0-py2.7.egg/tqdm/_tqdm.py", line 1315, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "./patcher/env/lib/python2.7/site-packages/tqdm-4.31.0-py2.7.egg/tqdm/_tqdm.py", line 250, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "./patcher/env/lib/python2.7/site-packages/tqdm-4.31.0-py2.7.egg/tqdm/_tqdm.py", line 243, in fp_write
    fp.write(_unicode(s))
  File "./patcher/env/lib/python2.7/site-packages/tqdm-4.31.0-py2.7.egg/tqdm/_utils.py", line 160, in write
    self, 'encoding')))
TypeError: encode() argument 1 must be string, not None
Exception TypeError: TypeError('encode() argument 1 must be string, not None',) in <bound method tqdm.__del__ of   0%|          | 0/11698 [00:00<?, ?it/s]> ignored
```

Previous version v4.30.0 works fine:
```python
  0%|          | 0/11700 [00:00<?, ?it/s]
 18%|#7        | 2088/11700 [00:09<00:42, 225.36it/s]
 33%|###3      | 3882/11700 [00:18<00:36, 213.90it/s]
 52%|#####2    | 6134/11700 [00:27<00:24, 223.09it/s]
 66%|######5   | 7694/11700 [00:37<00:20, 197.53it/s]
 85%|########4 | 9939/11700 [00:48<00:08, 202.26it/s]
100%|##########| 11700/11700 [00:55<00:00, 212.36it/s]
```

Line 61 from our code:
```python
pbar = filePaths.iteritems()
pbar = tqdm(pbar, mininterval=PearPatcherConfig.min_progress_bar_interval, total=len(filePaths))
```

**Comment by casperdcl** [comment]
@altendky I think this is related to #598 unfortunately

**Comment by casperdcl** [comment]
@beaverlyhills could you try the `tqdm:devel` branch?

**Comment by altendky** [comment]
I'll have to think tomorrow when my brain's not dead but I went ahead and made a blind guess (https://github.com/altendky/tqdm/commit/a9de36e7a3603dd2c9ad7a3605e289070fa70127).  We'll need to figure out the scenario which is causing this, seemingly that the file has a `.encoding` of `None`.

**Comment by altendky** [comment]
Ah well, that was easy...

```bash
$ python2 -c 'import sys; print(sys.stdout.encoding)' | cat
None
$ python3 -c 'import sys; print(sys.stdout.encoding)' | cat
UTF-8
```

@beaverlyhills, can you test out the commit referenced above and double check if it helps?  If so, I can add a test case and submit a real PR.

**Comment by beaverlyhills** [comment]
Can confirm that https://github.com/altendky/tqdm/commit/a9de36e7a3603dd2c9ad7a3605e289070fa70127 works.
Thank you for a quick fix!

**Comment by casperdcl** [comment]
@beaverlyhills I assume ff4fe92 also works as I'd mentioned?

**Comment by beaverlyhills** [comment]
https://github.com/tqdm/tqdm/commit/ff4fe9216e0a462dab56a4b9531342fedce12fdc works as well.
