### ISSUE TITLE
multiprocessing error 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by tomast95** [tqdm/tqdm#794]
tqdm instances, that are created in child processes (current_process().name != 'MainProcess') raises an error 'NoneType' object has no attribute 'write'

**Comment by casperdcl** [comment]
is this with the latest version of `tqdm`?

**Comment by Thurion** [comment]
I get the same error when executing the Python program from another process. I'm using 3.7.4 on Windows and tqdm 4.36.1 but in my case ``current_process().name`` returns ``MainProcess``.

Here's the stack trace:
```
Traceback (most recent call last):
  File "C:\Scripts\python\scramble.py", line 169, in _copyFiles
    with tqdm.tqdm(total=sizecounter, unit='B', unit_scale=True, unit_divisor=1024) as pbar:
  File "C:\Python\Python37\lib\site-packages\tqdm\std.py", line 1003, in __init__
    self.display()
  File "C:\Python\Python37\lib\site-packages\tqdm\std.py", line 1397, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "C:\Python\Python37\lib\site-packages\tqdm\std.py", line 304, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "C:\Python\Python37\lib\site-packages\tqdm\std.py", line 297, in fp_write
    fp.write(_unicode(s))
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by casperdcl** [comment]
could this be happening when a process is terminating and has cleared away the `write` method?

**Comment by Thurion** [comment]
Could be. I have batch file which is called by the other process. After I added ``START`` to the line that executes the python program it finished without any issues.

**Comment by Birmania** [comment]
Hi everyone,

One of the potential cause of this issue is the fact of using `tqdm` in a Window GUI application without console.
Here is the Workaround listed in my more detailed comment here : https://github.com/SergeyPirogov/webdriver_manager/issues/429#issuecomment-1426203643

```
class NullWriter:
    def write(self, data):
        pass

# Override stdout and stderr with NullWriter in GUI --noconsole mode
# This allow to avoid a bug where tqdm try to write on NoneType
if sys.stdout is None:
    sys.stdout = NullWriter()

if sys.stderr is None:
    sys.stderr = NullWriter()
```

Yours faithfully,
Birmania
