### ISSUE TITLE
AttributeError: 'tqdm_notebook' object has no attribute 'sp'

### ISSUE THREAD

**Issue by yarikoptic** [tqdm/tqdm#944]
This is an exception happening while handling an exception, as the main exception suggests -- I might have outdated jupyter/ipywidgets (and indeed I had no ipywidgets installed):

```
[INFO] AutomagicIO: retrieving file content of /home/yoh/proj/dandi/mvdm/data-formats/../MotivationalT-v2/R050/R050-2014-03-31_raw/R050-2014-03-31-CSC01a.ncs 
[WARNING] Still have 1 active progress bars when stopping 
[WARNING] Failed proxying open with ('../MotivationalT-v2/R050/R050-2014-03-31_raw/R050-2014-03-31-CSC01a.ncs',), {}: FloatProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html [notebook.py:status_printer:104] 
Exception ignored in: <function tqdm.__del__ at 0x7f61a4bf0d40>
Traceback (most recent call last):
  File "/home/yoh/anaconda-5.2.0-2.7/envs/mvdm-nept/lib/python3.7/site-packages/tqdm/std.py", line 1084, in __del__
    self.close()
  File "/home/yoh/anaconda-5.2.0-2.7/envs/mvdm-nept/lib/python3.7/site-packages/tqdm/notebook.py", line 245, in close
    self.sp(bar_style='danger')
AttributeError: 'tqdm_notebook' object has no attribute 'sp'
```
I expected tqdm to not issue that additional exception

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```
  4.45.0 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) 
[GCC 7.3.0] linux
  ```

**Comment by casperdcl** [comment]
sigh the infamous #548 again :)

at least it's merely extra verbosity in an external exception, but still...

**Comment by ShuoLiu-Max** [comment]
pip install ipywidgets

**Comment by casperdcl** [comment]
N.B. it seems to be a problem when a python process exits and doesn't clean up properly. Notice it says "Exception ignored" (while deleting an object) so isn't actually causing a crash.
